words = {

    "a": "letter A, bold, simple sans-serif",
    "able": "7yo girl, curly red hair, freckles, lifting heavy backpack",
    "aboard": "7yo girl, curly red hair, freckles, sitting in boat",
    "about": "7yo girl, curly red hair, freckles, pointing at speech bubble",
    "above": "7yo girl, curly red hair, freckles, looking up at kite",
    "absent": "7yo girl, curly red hair, freckles, standing next to empty chair",
    "accept": "7yo girl, curly red hair, freckles, holding out hands for gift",
    "accident": "7yo girl, curly red hair, freckles, looking at broken toy",
    "account": "7yo girl, curly red hair, freckles, holding piggy bank",
    "ache": "7yo girl, curly red hair, freckles, rubbing temples, pained face",
    "aching": "7yo girl, curly red hair, freckles, clutching stomach, wincing",
    "acorn": "acorn, with cap, on white background",
    "acre": "7yo girl, curly red hair, freckles, standing in small fenced field",
    "across": "7yo girl, curly red hair, freckles, walking across bridge",
    "act": "7yo girl, curly red hair, freckles, jumping with arms up",
    "acts": "7yo girl, curly red hair, freckles, jumping, another child clapping",
    "add": "7yo girl, curly red hair, freckles, holding plus sign",
    "address": "house with mailbox",
    "admire": "7yo girl, curly red hair, freckles, looking up with hands clasped",
    "adventure": "7yo girl, curly red hair, freckles, holding map and backpack",
    "afar": "7yo girl, curly red hair, freckles, pointing at distant mountain",
    "afraid": "7yo girl, curly red hair, freckles, hiding behind hands",
    "after": "7yo girl, curly red hair, freckles, pointing at clock showing later time",
    "afternoon": "sun in sky, indicating afternoon",
    "afterward": "7yo girl, curly red hair, freckles, pointing at clock showing later time",
    "afterwards": "7yo girl, curly red hair, freckles, pointing at clock showing later time",
    "again": "7yo girl, curly red hair, freckles, jumping, motion lines showing repetition",
    "against": "7yo girl, curly red hair, freckles, pushing against wall",
    "age": "7yo girl, curly red hair, freckles, holding birthday cake with candles",
    "aged": "7yo girl, curly red hair, freckles, with gray hair wig, holding cane",
    "ago": "7yo girl, curly red hair, freckles, pointing at calendar with crossed-out date",
    "agree": "7yo girl, curly red hair, freckles, nodding head, thumbs up",
    "ah": "7yo girl, curly red hair, freckles, hands on cheeks, surprised expression",
    "ahead": "7yo girl, curly red hair, freckles, pointing forward with arm extended",
    "aid": "7yo girl, curly red hair, freckles, helping another child up from ground",
    "aim": "7yo girl, curly red hair, freckles, holding toy bow, aiming at target",
    "air": "7yo girl, curly red hair, freckles, blowing bubbles, visible bubbles floating",
    "airfield": "small airplane on runway, control tower in background",
    "airplane": "airplane with wings, tail, and windows",
    "airport": "airport terminal building, airplane parked outside",
    "airship": "airship, classic blimp shape with fins and gondola",
    "airy": "7yo girl, curly red hair, freckles, floating, surrounded by floating bubbles",
    "alarm": "alarm clock with bells, ringing",
    "alike": "7yo girl, curly red hair, freckles, pointing at two identical teddy bears",
    "alive": "7yo girl, curly red hair, freckles, wide eyes, surrounded by growing plants",
    "all": "7yo girl, curly red hair, freckles, arms open wide, surrounded by toys",
    "alley": "alley, narrow path between buildings",
    "alligator": "alligator, simple shape with visible teeth",
    "allow": "7yo girl, curly red hair, freckles, giving thumbs up",
    "almost": "7yo girl, curly red hair, freckles, reaching for balloon floating away",
    "alone": "7yo girl, curly red hair, freckles, sitting alone on bench",
    "along": "7yo girl, curly red hair, freckles, walking beside picket fence",
    "aloud": "7yo girl, curly red hair, freckles, speaking, sound waves around mouth",
    "already": "7yo girl, curly red hair, freckles, holding finished puzzle, smiling",
    "also": "7yo girl, curly red hair, freckles, holding apple and also banana",
    "always": "7yo girl, curly red hair, freckles, jumping rope, motion lines showing repetition",
    "am": "7yo girl, curly red hair, freckles, holding sign with word 'am'",
    "america": "simplified map of America, recognizable shapes",
    "american": "7yo girl, curly red hair, freckles, wearing flag-themed outfit",
    "among": "7yo girl, curly red hair, freckles, standing among group of objects",
    "amount": "7yo girl, curly red hair, freckles, holding pile of objects",
    "an": "7yo girl, curly red hair, freckles, holding sign with word 'an'",
    "and": "7yo girl, curly red hair, freckles, holding two objects together",
    "angel": "simple angel figure, wings and halo",
    "anger": "7yo girl, curly red hair, freckles, frowning, eyebrows furrowed, clenched fists",
    "angry": "7yo girl, curly red hair, freckles, frowning, eyebrows furrowed, clenched fists",
    "animal": "dog, sitting, tail wagging",
    "another": "7yo girl, curly red hair, freckles, pointing at second apple",
    "answer": "piece of paper, checkmark on it",
    "ant": "ant, walking, antennae visible",
    "any": "7yo girl, curly red hair, freckles, pointing at group of apples",
    "anybody": "7yo girl, curly red hair, freckles, pointing at group of people",
    "anyhow": "7yo girl, curly red hair, freckles, shrugging, arrows pointing in different directions",
    "anyone": "7yo girl, curly red hair, freckles, open arms, diverse silhouettes around",
    "anything": "7yo girl, curly red hair, freckles, holding magic wand, sparkles, question marks",
    "anyway": "7yo girl, curly red hair, freckles, walking forward, path splitting into multiple directions",
    "anywhere": "7yo girl, curly red hair, freckles, map and compass, landmarks around",
    "apart": "7yo girl, curly red hair, freckles, hands apart, objects between",
    "apartment": "apartment building, windows and door",
    "ape": "ape, sitting on a branch",
    "apiece": "7yo girl, curly red hair, freckles, holding two apples, pointing at each",
    "appear": "7yo girl, curly red hair, freckles, peeking from behind tree",
    "apple": "apple, with leaf and stem",
    "april": "7yo girl, curly red hair, freckles, holding umbrella, rain falling",
    "apron": "7yo girl, curly red hair, freckles, wearing apron, holding spoon",
    "are": "7yo girl, curly red hair, freckles, pointing at two equal stacks of blocks",
    "aren't": "7yo girl, curly red hair, freckles, shaking head, pointing at unequal stacks of blocks",
    "arise": "7yo girl, curly red hair, freckles, standing up from chair",
    "arithmetic": "7yo girl, curly red hair, freckles, holding chalkboard with plus and minus signs",
    "arm": "arm, with hand and fingers",
    "armful": "arms holding bundle of books",
    "army": "group of soldiers in uniform, standing in line",
    "arose": "7yo girl, curly red hair, freckles, standing up from chair",
    "around": "7yo girl, curly red hair, freckles, walking in circle around tree",
    "arrange": "7yo girl, curly red hair, freckles, organizing toys on shelf",
    "arrive": "7yo girl, curly red hair, freckles, stepping off bus",
    "arrived": "7yo girl, curly red hair, freckles, standing at door, suitcase beside",
    "arrow": "arrow, pointing right, simple shape",
    "art": "7yo girl, curly red hair, freckles, painting at easel, brush in hand",
    "artist": "7yo girl, curly red hair, freckles, wearing beret, holding paintbrush",
    "as": "7yo girl, curly red hair, freckles, holding apple, comparing to orange",
    "ash": "pile of gray ash, simple texture",
    "ashes": "larger pile of gray ashes, scattered",
    "aside": "7yo girl, curly red hair, freckles, pushing book to side, hand gesture",
    "ask": "7yo girl, curly red hair, freckles, raising hand, question mark above",
    "asleep": "7yo girl, curly red hair, freckles, sleeping, Zzz above head",
    "at": "7yo girl, curly red hair, freckles, pointing at house",
    "ate": "7yo girl, curly red hair, freckles, eating apple, crumbs around",
    "attack": "7yo girl, curly red hair, freckles, shielding face, toy dinosaur lunging",
    "attend": "7yo girl, curly red hair, freckles, sitting at desk, book open",
    "attention": "7yo girl, curly red hair, freckles, eyes wide, magnifying glass over book",
    "august": "7yo girl, curly red hair, freckles, holding ice cream, beach ball nearby",
    "aunt": "woman, warm smile, hugging child",
    "author": "person, sitting at desk, writing in book",
    "auto": "car, four wheels, windows",
    "automobile": "car, four wheels, windows, headlights",
    "autumn": "7yo girl, curly red hair, freckles, standing under tree, colorful leaves falling",
    "avenue": "wide road, trees on both sides",
    "awake": "7yo girl, curly red hair, freckles, sitting up in bed, eyes open",
    "awaken": "7yo girl, curly red hair, freckles, sitting up in bed, eyes opening",
}