words = {

    "a": "letter A, bold, simple sans-serif",
    "able": "7yo girl, curly red hair, freckles, lifting heavy backpack",
    "aboard": "7yo girl, curly red hair, freckles, sitting in boat",
    "about": "7yo girl, curly red hair, freckles, pointing at speech bubble",
    "above": "7yo girl, curly red hair, freckles, looking up at kite",
    "absent": "7yo girl, curly red hair, freckles, standing next to empty chair",
    "accept": "7yo girl, curly red hair, freckles, holding out hands for gift",
    "accident": "7yo girl, curly red hair, freckles, looking at broken toy",
    "account": "7yo girl, curly red hair, freckles, holding piggy bank",
    "ache": "7yo girl, curly red hair, freckles, rubbing temples, pained face",
    "aching": "7yo girl, curly red hair, freckles, clutching stomach, wincing",
    "acorn": "acorn, with cap, on white background",
    "acre": "7yo girl, curly red hair, freckles, standing in small fenced field",
    "across": "7yo girl, curly red hair, freckles, walking across bridge",
    "act": "7yo girl, curly red hair, freckles, jumping with arms up",
    "acts": "7yo girl, curly red hair, freckles, jumping, another child clapping",
    "add": "7yo girl, curly red hair, freckles, holding plus sign",
    "address": "house with mailbox",
    "admire": "7yo girl, curly red hair, freckles, looking up with hands clasped",
    "adventure": "7yo girl, curly red hair, freckles, holding map and backpack",
    "afar": "7yo girl, curly red hair, freckles, pointing at distant mountain",
    "afraid": "7yo girl, curly red hair, freckles, hiding behind hands",
    "after": "7yo girl, curly red hair, freckles, pointing at clock showing later time",
    "afternoon": "sun in sky, indicating afternoon",
    "afterward": "7yo girl, curly red hair, freckles, pointing at clock showing later time",
    "afterwards": "7yo girl, curly red hair, freckles, pointing at clock showing later time",
    "again": "7yo girl, curly red hair, freckles, jumping, motion lines showing repetition",
    "against": "7yo girl, curly red hair, freckles, pushing against wall",
    "age": "7yo girl, curly red hair, freckles, holding birthday cake with candles",
    "aged": "7yo girl, curly red hair, freckles, with gray hair wig, holding cane",
    "ago": "7yo girl, curly red hair, freckles, pointing at calendar with crossed-out date",
    "agree": "7yo girl, curly red hair, freckles, nodding head, thumbs up",
    "ah": "7yo girl, curly red hair, freckles, hands on cheeks, surprised expression",
    "ahead": "7yo girl, curly red hair, freckles, pointing forward with arm extended",
    "aid": "7yo girl, curly red hair, freckles, helping another child up from ground",
    "aim": "7yo girl, curly red hair, freckles, holding toy bow, aiming at target",
    "air": "7yo girl, curly red hair, freckles, blowing bubbles, visible bubbles floating",
    "airfield": "small airplane on runway, control tower in background",
    "airplane": "airplane with wings, tail, and windows",
    "airport": "airport terminal building, airplane parked outside",
    "airship": "airship, classic blimp shape with fins and gondola",
    "airy": "7yo girl, curly red hair, freckles, floating, surrounded by floating bubbles",
    "alarm": "alarm clock with bells, ringing",
    "alike": "7yo girl, curly red hair, freckles, pointing at two identical teddy bears",
    "alive": "7yo girl, curly red hair, freckles, wide eyes, surrounded by growing plants",
    "all": "7yo girl, curly red hair, freckles, arms open wide, surrounded by toys",
    "alley": "alley, narrow path between buildings",
    "alligator": "alligator, simple shape with visible teeth",
    "allow": "7yo girl, curly red hair, freckles, giving thumbs up",
    "almost": "7yo girl, curly red hair, freckles, reaching for balloon floating away",
    "alone": "7yo girl, curly red hair, freckles, sitting alone on bench",
    "along": "7yo girl, curly red hair, freckles, walking beside picket fence",
    "aloud": "7yo girl, curly red hair, freckles, speaking, sound waves around mouth",
    "already": "7yo girl, curly red hair, freckles, holding finished puzzle, smiling",
    "also": "7yo girl, curly red hair, freckles, holding apple and also banana",
    "always": "7yo girl, curly red hair, freckles, jumping rope, motion lines showing repetition",
    "am": "7yo girl, curly red hair, freckles, holding sign with word 'am'",
    "america": "simplified map of America, recognizable shapes",
    "american": "7yo girl, curly red hair, freckles, wearing flag-themed outfit",
    "among": "7yo girl, curly red hair, freckles, standing among group of objects",
    "amount": "7yo girl, curly red hair, freckles, holding pile of objects",
    "an": "7yo girl, curly red hair, freckles, holding sign with word 'an'",
    "and": "7yo girl, curly red hair, freckles, holding two objects together",
    "angel": "simple angel figure, wings and halo",
    "anger": "7yo girl, curly red hair, freckles, frowning, eyebrows furrowed, clenched fists",
    "angry": "7yo girl, curly red hair, freckles, frowning, eyebrows furrowed, clenched fists",
    "animal": "dog, sitting, tail wagging",
    "another": "7yo girl, curly red hair, freckles, pointing at second apple",
    "answer": "piece of paper, checkmark on it",
    "ant": "ant, walking, antennae visible",
    "any": "7yo girl, curly red hair, freckles, pointing at group of apples",
    "anybody": "7yo girl, curly red hair, freckles, pointing at group of people",
    "anyhow": "7yo girl, curly red hair, freckles, shrugging, arrows pointing in different directions",
    "anyone": "7yo girl, curly red hair, freckles, open arms, diverse silhouettes around",
    "anything": "7yo girl, curly red hair, freckles, holding magic wand, sparkles, question marks",
    "anyway": "7yo girl, curly red hair, freckles, walking forward, path splitting into multiple directions",
    "anywhere": "7yo girl, curly red hair, freckles, map and compass, landmarks around",
    "apart": "7yo girl, curly red hair, freckles, hands apart, objects between",
    "apartment": "apartment building, windows and door",
    "ape": "ape, sitting on a branch",
    "apiece": "7yo girl, curly red hair, freckles, holding two apples, pointing at each",
    "appear": "7yo girl, curly red hair, freckles, peeking from behind tree",
    "apple": "apple, with leaf and stem",
    "april": "7yo girl, curly red hair, freckles, holding umbrella, rain falling",
    "apron": "7yo girl, curly red hair, freckles, wearing apron, holding spoon",
    "are": "7yo girl, curly red hair, freckles, pointing at two equal stacks of blocks",
    "aren't": "7yo girl, curly red hair, freckles, shaking head, pointing at unequal stacks of blocks",
    "arise": "7yo girl, curly red hair, freckles, standing up from chair",
    "arithmetic": "7yo girl, curly red hair, freckles, holding chalkboard with plus and minus signs",
    "arm": "arm, with hand and fingers",
    "armful": "arms holding bundle of books",
    "army": "group of soldiers in uniform, standing in line",
    "arose": "7yo girl, curly red hair, freckles, standing up from chair",
    "around": "7yo girl, curly red hair, freckles, walking in circle around tree",
    "arrange": "7yo girl, curly red hair, freckles, organizing toys on shelf",
    "arrive": "7yo girl, curly red hair, freckles, stepping off bus",
    "arrived": "7yo girl, curly red hair, freckles, standing at door, suitcase beside",
    "arrow": "arrow, pointing right, simple shape",
    "art": "7yo girl, curly red hair, freckles, painting at easel, brush in hand",
    "artist": "7yo girl, curly red hair, freckles, wearing beret, holding paintbrush",
    "as": "7yo girl, curly red hair, freckles, holding apple, comparing to orange",
    "ash": "pile of gray ash, simple texture",
    "ashes": "larger pile of gray ashes, scattered",
    "aside": "7yo girl, curly red hair, freckles, pushing book to side, hand gesture",
    "ask": "7yo girl, curly red hair, freckles, raising hand, question mark above",
    "asleep": "7yo girl, curly red hair, freckles, sleeping, Zzz above head",
    "at": "7yo girl, curly red hair, freckles, pointing at house",
    "ate": "7yo girl, curly red hair, freckles, eating apple, crumbs around",
    "attack": "7yo girl, curly red hair, freckles, shielding face, toy dinosaur lunging",
    "attend": "7yo girl, curly red hair, freckles, sitting at desk, book open",
    "attention": "7yo girl, curly red hair, freckles, eyes wide, magnifying glass over book",
    "august": "7yo girl, curly red hair, freckles, holding ice cream, beach ball nearby",
    "aunt": "woman, warm smile, hugging child",
    "author": "person, sitting at desk, writing in book",
    "auto": "car, four wheels, windows",
    "automobile": "car, four wheels, windows, headlights",
    "autumn": "7yo girl, curly red hair, freckles, standing under tree, colorful leaves falling",
    "avenue": "wide road, trees on both sides",
    "awake": "7yo girl, curly red hair, freckles, sitting up in bed, eyes open",
    "awaken": "7yo girl, curly red hair, freckles, sitting up in bed, eyes opening",
    "away": "7yo girl, curly red hair, freckles, walking off into distance",
    "awful": "7yo girl, curly red hair, freckles, holding nose, garbage can visible",
    "awfully": "7yo girl, curly red hair, freckles, exaggerated expression of disgust, rotten food visible",
    "awhile": "7yo girl, curly red hair, freckles, sitting on floor, hourglass visible",
    "ax": "ax with wooden handle and metal blade",
    "axe": "axe with wooden handle and metal blade",
    "baa": "sheep with open mouth, sound waves visible",
    "babe": "baby in crib, smiling, with blanket",
    "babies": "baby, simple, smiling",
    "back": "person, back view, simple",
    "background": "7yo girl, curly red hair, freckles, standing in front of simple landscape",
    "backward": "7yo girl, curly red hair, freckles, walking backward",
    "backwards": "7yo girl, curly red hair, freckles, walking backward",
    "bacon": "bacon, strip, simple",
    "bad": "7yo girl, curly red hair, freckles, frowning, broken toy visible",
    "badge": "badge, simple, centered",
    "badly": "7yo girl, curly red hair, freckles, frowning, dropping a ball",
    "bag": "bag, with zipper and handle",
    "bake": "7yo girl, curly red hair, freckles, mixing batter in bowl",
    "baker": "baker, white hat and apron, holding bread loaf",
    "bakery": "bakery storefront, bread loaves in window",
    "baking": "7yo girl, curly red hair, freckles, putting tray in oven",
    "ball": "ball, round with classic pattern",
    "balloon": "balloon, round, with string",
    "banana": "banana, with stem and brown tip",
    "band": "elastic band, stretched",
    "bandage": "white bandage, wrapped around finger",
    "bang": "7yo girl, curly red hair, freckles, covering ears, explosion in background",
    "banjo": "banjo, round body, long neck, strings",
    "bank": "river bank, grassy slope, water visible",
    "banker": "man in suit, holding briefcase, tie",
    "bar": "chocolate bar, rectangular, sections visible",
    "barber": "barber, scissors in hand, client in chair",
    "bare": "7yo girl, curly red hair, freckles, rolling up sleeves, bare arms visible",
    "barefoot": "7yo girl, curly red hair, freckles, sitting, bare feet visible",
    "barely": "7yo girl, curly red hair, freckles, straining, barely lifting small box",
    "bark": "tree trunk, rough bark texture visible",
    "barn": "barn, red roof, simple shape",
    "barrel": "wooden barrel, metal hoops visible",
    "base": "pyramid, wide base clearly visible",
    "baseball": "baseball, with red stitching",
    "basement": "basement door, stairs visible",
    "basket": "woven basket, with handle",
    "bat": "bat, hanging upside down",
    "batch": "7yo girl, curly red hair, freckles, holding tray of cookies",
    "bath": "bathtub, with water",
    "bathe": "7yo girl, curly red hair, freckles, in bathtub, bubbles",
    "bathing": "7yo girl, curly red hair, freckles, bathing, rubber duck",
    "bathroom": "toilet, simple, white",
    "bathtub": "bathtub, water, bubbles",
    "battle": "7yo girl, curly red hair, freckles, holding toy sword, shield visible",
    "battleship": "battleship, cannons, flag",
    "bay": "bay, curved shoreline, boat",
    "be": "7yo girl, curly red hair, freckles, standing still",
    "beach": "beach, sand, waves, umbrella",
    "bead": "bead, hole, thread",
    "beam": "wooden beam, horizontal, visible grain",
    "bean": "green bean pod, split open, beans visible",
    "bear": "brown bear, standing, simple",
    "beard": "man, long curly beard, simple",
    "beast": "lion head, mane, simple",
    "beat": "7yo girl, curly red hair, freckles, hitting drum with stick",
    "beating": "7yo girl, curly red hair, freckles, hitting drum repeatedly",
    "beautiful": "7yo girl, curly red hair, freckles, admiring flower",
    "beautify": "7yo girl, curly red hair, freckles, arranging flowers in vase",
    "beauty": "7yo girl, curly red hair, freckles, admiring flower",
    "became": "7yo girl, curly red hair, freckles, caterpillar becoming butterfly",
    "because": "7yo girl, curly red hair, freckles, pointing at rain cloud, holding umbrella",
    "become": "7yo girl, curly red hair, freckles, putting on superhero cape",
    "becoming": "7yo girl, curly red hair, freckles, half caterpillar, half butterfly",
    "bed": "bed, with pillows and blanket",
    "bedbug": "bedbug, on bed sheet",
    "bedroom": "bedroom, bed with pillows and blanket",
    "bedspread": "bedspread, folded on bed",
    "bedtime": "7yo girl, curly red hair, freckles, yawning, holding teddy bear",
    "bee": "bee, striped body, wings",
    "beech": "beech tree, smooth bark, oval leaves",
    "beef": "beef, raw steak on plate",
    "beefsteak": "beefsteak, grilled, with marks",
    "beehive": "beehive, honeycomb pattern",
    "been": "7yo girl, curly red hair, freckles, pointing at footprint in sand",
    "beer": "glass of beer, foam on top",
    "beet": "beet, with green leaves attached",
    "before": "7yo girl, curly red hair, freckles, pointing at clock showing earlier time",
    "beg": "7yo girl, curly red hair, freckles, kneeling, hands clasped in prayer",
    "began": "7yo girl, curly red hair, freckles, pointing at starting line on track",
    "beggar": "person in tattered clothes, holding cup, sitting on ground",
    "begged": "7yo girl, curly red hair, freckles, kneeling, hands clasped in prayer, tears in eyes",
    "begin": "7yo girl, curly red hair, freckles, starting to run",
    "beginning": "7yo girl, curly red hair, freckles, standing at start of path",
    "begun": "7yo girl, curly red hair, freckles, running mid-stride",
    "behave": "7yo girl, curly red hair, freckles, sitting quietly with hands folded",
    "behind": "7yo girl, curly red hair, freckles, peeking from behind tree",
    "being": "7yo girl, curly red hair, freckles, standing calmly",
    "believe": "7yo girl, curly red hair, freckles, hands together in hope",
    "bell": "school bell, with handle",
    "belong": "7yo girl, curly red hair, freckles, placing toy in toy box",
    "below": "7yo girl, curly red hair, freckles, pointing down at ball on ground",
    "belt": "belt with buckle, hanging straight",
    "bench": "wooden bench with backrest",
    "bend": "7yo girl, curly red hair, freckles, bending at waist",
    "beneath": "7yo girl, curly red hair, freckles, looking under table",
    "bent": "bent straw in cup",
    "berries": "pile of mixed berries",
    "berry": "berry, with stem and leaf",
    "beside": "7yo girl, curly red hair, freckles, standing beside chair",
    "besides": "7yo girl, curly red hair, freckles, pointing at group of toys, one extra toy",
    "best": "7yo girl, curly red hair, freckles, holding trophy, medal around neck",
    "bet": "7yo girl, curly red hair, freckles, holding playing cards, chips on table",
    "better": "7yo girl, curly red hair, freckles, pointing at bigger apple vs smaller apple",
    "between": "7yo girl, curly red hair, freckles, standing between two trees",
    "bib": "7yo girl, curly red hair, freckles, wearing colorful bib, spaghetti on tray",
    "bible": "open book, cross symbol on cover",
    "bicycle": "bicycle, two wheels, handlebars",
    "bid": "7yo girl, curly red hair, freckles, holding up numbered card",
    "big": "7yo girl, curly red hair, freckles, next to oversized teddy bear",
    "bigger": "7yo girl, curly red hair, freckles, pointing at larger ball",
    "bill": "paper bill, dollar sign visible",
    "billboard": "rectangular billboard, simple ad visible",
    "bin": "open bin, lid visible",
    "bind": "7yo girl, curly red hair, freckles, tying rope around box",
    "bird": "bird, perched on branch",
    "birth": "7yo girl, curly red hair, freckles, holding newborn baby",
    "birthday": "birthday cake, candles lit",
    "biscuit": "biscuit, round, with chocolate chips",
    "bit": "small piece of apple, bitten edge visible",
    "bite": "7yo girl, curly red hair, freckles, biting apple",
    "biting": "7yo girl, curly red hair, freckles, teeth on apple, biting",
    "bitter": "lemon, with visible cut",
    "black": "7yo girl, curly red hair, freckles, holding black square",
    "blackberry": "cluster of blackberries",
    "blackbird": "blackbird, with visible beak and tail",
    "blackboard": "blackboard, with chalk marks",
    "blackness": "7yo girl, curly red hair, freckles, in dark room, flashlight visible",
    "blacksmith": "blacksmith, with hammer and anvil",
    "blame": "7yo girl, curly red hair, freckles, pointing at another child",
    "blank": "7yo girl, curly red hair, freckles, looking at empty white paper",
    "blanket": "folded blanket, soft texture, tassels visible",
    "blast": "7yo girl, curly red hair, freckles, covering ears, explosion in background",
    "blaze": "7yo girl, curly red hair, freckles, looking at large flames",
    "bleed": "7yo girl, curly red hair, freckles, bandage on knee, small red spot",
    "bless": "7yo girl, curly red hair, freckles, hands together in prayer",
    "blessing": "7yo girl, curly red hair, freckles, receiving gift box with bow",
    "blew": "7yo girl, curly red hair, freckles, blowing out birthday candles",
    "blind": "7yo girl, curly red hair, freckles, holding white cane, dark glasses",
    "blindfold": "7yo girl, curly red hair, freckles, wearing black blindfold",
    "blinds": "window with closed horizontal blinds",
    "block": "wooden toy block, red, with letter A",
    "blood": "cartoon drop of blood, bright red",
    "bloom": "7yo girl, curly red hair, freckles, watching flower bloom",
    "blossom": "cherry blossom flower, pink petals",
    "blot": "ink blot, black, on white paper",
    "blow": "7yo girl, curly red hair, freckles, blowing, breath cloud visible",
    "blue": "7yo girl, curly red hair, freckles, holding blue balloon",
    "blueberry": "blueberry, with crown and stem",
    "bluebird": "bluebird, blue feathers, orange chest",
    "blush": "7yo girl, curly red hair, freckles, blushing, red cheeks",
    "board": "wooden board, visible grain",
    "boast": "7yo girl, curly red hair, freckles, boasting, arms crossed, proud smile",
    "boat": "boat, simple, with sail",
    "bob": "girl with bob haircut, short rounded style",
    "bobwhite": "bobwhite bird, small quail with markings",
    "bodies": "multiple simple human figures, stick style",
    "body": "simple human body outline, stick figure",
    "boil": "7yo girl, curly red hair, freckles, watching pot with bubbles",
    "boiler": "cylindrical boiler, pipes attached",
    "bold": "7yo girl, curly red hair, freckles, standing tall, hands on hips",
    "bone": "simple bone shape, dog bone style",
    "bonnet": "baby, wearing bonnet, tied under chin",
    "boo": "7yo girl, curly red hair, freckles, jumping back, hands up in surprise",
    "book": "open book, visible pages, simple cover",
    "bookcase": "tall wooden bookcase, books visible on shelves",
    "bookkeeper": "person at desk, books, calculator, glasses",
    "boom": "7yo girl, curly red hair, freckles, covering ears, sound wave lines",
    "boot": "boot, laces, thick sole",
    "born": "7yo girl, curly red hair, freckles, holding baby in blanket, hospital tag visible",
    "borrow": "7yo girl, curly red hair, freckles, handing book to boy, boy handing toy back",
    "boss": "adult man, suit, tie, name tag 'BOSS'",
    "both": "7yo girl, curly red hair, freckles, holding apple and banana",
    "bother": "7yo girl, curly red hair, freckles, frowning, mosquito buzzing near",
    "bottle": "bottle, with cap and label",
    "bottom": "bottom of glass, water visible",
    "bought": "7yo girl, curly red hair, freckles, holding shopping bag, items peeking out",
    "bounce": "7yo girl, curly red hair, freckles, mid-bounce, hair flying up",
    "bow": "bow, ribbon, loops, tails",
    "bow-wow": "dog, open mouth, barking",
    "bowl": "bowl, round, curved sides",
    "box": "box, cube, lid slightly open",
    "boxcar": "boxcar, train, sliding doors",
    "boxer": "boxer dog, square muzzle, muscular",
    "boxes": "boxes, stack, three sizes",
    "boy": "7yo boy, short hair, simple clothes",
    "boyhood": "7yo boy, curly hair, freckles, holding toy car and school bag",
    "bracelet": "bracelet, with small heart charm",
    "brain": "brain, simplified, with visible folds",
    "brake": "bicycle brake lever, with visible cable",
    "bran": "pile of bran, with wheat stalk",
    "branch": "tree branch, with green leaves and small bird",
    "brass": "brass trumpet, with visible shine",
    "brave": "7yo boy, curly hair, freckles, standing tall with shield",
    "bread": "loaf of bread, slice cut off",
    "break": "7yo girl, curly red hair, freckles, breaking stick over knee",
    "breakfast": "breakfast plate, eggs, toast, coffee cup",
    "breast": "simple outline of chest area",
    "breath": "visible breath cloud in cold air",
    "breathe": "7yo girl, curly red hair, freckles, taking deep breath, chest expanding",
    "breeze": "tree, leaves rustling in gentle breeze",
    "brick": "red brick, clear texture, simple shape",
    "bride": "bride, wedding dress, veil",
    "bridge": "bridge, arch, water below",
    "bright": "7yo girl, curly red hair, freckles, squinting, sun shining behind",
    "brightness": "7yo girl, curly red hair, freckles, shielding eyes, bright light source",
    "bring": "7yo girl, curly red hair, freckles, carrying gift box, walking forward",
    "broad": "7yo girl, curly red hair, freckles, standing next to wide tree trunk",
    "broadcast": "7yo girl, curly red hair, freckles, holding microphone, speaking",
    "broke": "7yo girl, curly red hair, freckles, holding broken stick, surprised",
    "broken": "7yo girl, curly red hair, freckles, holding broken toy car, wheel missing",
    "brook": "brook, small stream flowing over rocks",
    "broom": "broom, long handle, bristles visible",
    "brother": "boy, short hair, simple clothes",
    "brought": "7yo girl, curly red hair, freckles, carrying box",
    "brown": "brown teddy bear",
    "brush": "paintbrush, bristles visible",
    "bubble": "bubble, floating, with shine",
    "bucket": "bucket, with handle",
    "buckle": "belt buckle, rectangular",
    "bud": "flower bud, closed",
    "buffalo": "buffalo, large horns",
    "bug": "bug, six legs, antennae",
    "buggy": "baby buggy, four wheels",
    "build": "7yo girl, curly red hair, freckles, building with blocks",
    "building": "building, multiple windows",
    "built": "7yo girl, curly red hair, freckles, pointing at finished house",
    "bulb": "light bulb, with filament visible",
    "bull": "bull, with horns and hump",
    "bullet": "bullet, pointed tip visible",
    "bum": "child sitting, bottom visible",
    "bumblebee": "bumblebee, black and yellow stripes",
    "bump": "raised bump on surface",
    "bun": "round bread bun",
    "bunch": "bunch of bananas, tied together",
    "bundle": "bundle of sticks, tied with string",
    "bunny": "bunny, long ears, sitting upright",
    "burn": "7yo girl, curly red hair, freckles, holding candle, flame visible",
    "burst": "7yo girl, curly red hair, freckles, surprised, balloon bursting",
    "bury": "7yo girl, curly red hair, freckles, digging hole, toy partially buried",
    "bus": "school bus, yellow, with windows",
    "bush": "bush, green, with leaves",
    "bushel": "bushel basket, apples overflowing",
    "business": "7yo girl, curly red hair, freckles, standing in front of shop front",
    "busy": "7yo girl, curly red hair, freckles, juggling books, phone, and backpack",
    "but": "7yo girl, curly red hair, freckles, pointing at speech bubble with contrast",
    "butcher": "7yo girl, curly red hair, freckles, wearing apron, holding cleaver, meat on counter",
    "butt": "cigarette butt, crushed on ground",
    "butter": "stick of butter, wrapper partially peeled",
    "buttercup": "buttercup flower, yellow petals, green stem",
    "butterfly": "butterfly, spread wings, visible patterns",
    "buttermilk": "glass of buttermilk, visible liquid texture",
    "butterscotch": "butterscotch candy, visible wrapper, golden color",
    "button": "button, visible holes, thread",
    "buttonhole": "buttonhole, visible stitching, button partially inserted",
    "buy": "7yo girl, curly red hair, freckles, holding money, pointing at product",
    "buzz": "bee, visible wings in motion, striped body",
    "by": "7yo girl, curly red hair, freckles, standing next to tree",
    "bye": "7yo girl, curly red hair, freckles, waving hand",
    "cab": "yellow taxi car, roof light, 'TAXI' sign",
    "cabbage": "cabbage head, green, layered leaves",
    "cabin": "wooden cabin, simple, door, window",
    "cabinet": "kitchen cabinet, rectangular, handle",
    "cackle": "7yo girl, curly red hair, freckles, laughing loudly, open mouth, witch hat slightly visible",
    "cage": "metal cage, bars, door",
    "cake": "round cake, frosting, candles",
    "calendar": "calendar, hanging on wall, visible dates",
    "calf": "calf, baby cow, large eyes",
    "call": "7yo girl, curly red hair, freckles, shouting, hands around mouth",
    "caller": "person, holding phone to ear, talking",
    "calling": "7yo girl, curly red hair, freckles, holding phone, talking",
    "came": "7yo girl, curly red hair, freckles, walking through door",
    "camel": "camel, two humps, desert background",
    "camp": "tent, campfire nearby, camping",
    "campfire": "campfire, flames, logs",
    "can": "metal can, lid",
    "can't": "7yo girl, curly red hair, freckles, shaking head, crossed arms",
    "canal": "canal, narrow waterway, small boats",
    "canary": "yellow canary, perch",
    "candle": "lit candle, flame",
    "candlestick": "candlestick, candle",
    "candy": "wrapped candy, wrapper",
    "cane": "cane, curved handle, simple design",
    "cannon": "cannon, wheels, barrel",
    "cannot": "7yo girl, curly red hair, freckles, crossing arms, shaking head",
    "canoe": "canoe, paddles, simple design",
    "canyon": "canyon, steep walls, simple design",
    "cap": "cap, brim, simple design",
    "cape": "cape, collar, simple design",
    "capital": "capital, skyline, flag, simple design",
    "captain": "captain, uniform, captain's hat",
    "car": "car, four wheels, windows",
    "card": "card, rectangular, visible design",
    "cardboard": "cardboard box, visible texture",
    "care": "7yo girl, curly red hair, freckles, holding plant carefully",
    "careful": "7yo girl, curly red hair, freckles, walking slowly, arms outstretched",
    "careless": "7yo girl, curly red hair, freckles, dropping object, running",
    "carelessness": "7yo girl, curly red hair, freckles, spilling water, not paying attention",
    "carload": "car filled with boxes and suitcases",
    "carpenter": "carpenter, hammer and saw in hand",
    "carpet": "carpet, floral pattern, rolled edge",
    "carriage": "horse-drawn carriage, large wheels",
    "carrot": "carrot, with green leaves",
    "carry": "7yo girl, curly red hair, freckles, carrying heavy backpack",
    "cart": "cart, two wheels, boxes inside",
    "carve": "7yo girl, curly red hair, freckles, carving wood with knife",
    "case": "suitcase, handle visible",
    "cash": "stack of dollar bills",
    "cashier": "cashier, standing at checkout counter",
    "castle": "castle, towers, flag on top",
    "cat": "cat, sitting, tail curled",
    "catbird": "catbird, perched on branch",
    "catch": "7yo girl, curly red hair, freckles, catching ball",
    "catcher": "baseball catcher, mask and mitt",
    "caterpillar": "caterpillar, with segmented body and legs",
    "catfish": "catfish, with long whiskers",
    "catsup": "ketchup bottle, with label",
    "cattle": "cow, with spots and horns",
    "caught": "7yo girl, curly red hair, freckles, catching ball",
    "cause": "7yo girl, curly red hair, freckles, pointing at broken vase",
    "cave": "cave entrance, with rocks",
    "ceiling": "ceiling, with light fixture",
    "cell": "jail cell, small room with barred window",
    "cellar": "cellar, wooden stairs leading down to shelves",
    "cent": "US cent coin, round, copper color, '1' visible",
    "center": "7yo girl, curly red hair, freckles, standing in middle of circle",
    "cereal": "bowl of cereal, spoon, milk splash",
    "certain": "7yo girl, curly red hair, freckles, nodding, thumbs up",
    "certainly": "7yo girl, curly red hair, freckles, confidently pointing forward",
    "chain": "metal chain, few connected links, simple",
    "chair": "chair, four legs, backrest",
    "chalk": "chalk, worn tip",
    "champion": "7yo girl, curly red hair, freckles, holding trophy",
    "chance": "7yo girl, curly red hair, freckles, pointing at spinning wheel",
    "change": "7yo girl, curly red hair, freckles, exchanging toy car for doll",
    "chap": "hand, crack on knuckle",
    "charge": "7yo girl, curly red hair, freckles, plugging in device",
    "charm": "7yo girl, curly red hair, freckles, wearing charm bracelet",
    "chart": "bar chart, three colored bars, different heights",
    "chase": "7yo girl, curly red hair, freckles, running, chasing butterfly",
    "chatter": "7yo girl, curly red hair, freckles, talking, three speech bubbles around",
    "cheap": "7yo girl, curly red hair, freckles, holding price tag, '1$' visible",
    "cheat": "7yo girl, curly red hair, freckles, peeking at hidden answers under paper",
    "check": "7yo girl, curly red hair, freckles, holding checklist, checkmarks on items",
    "checkers": "checkerboard, red and black pieces, some on board",
    "cheek": "close-up of face, cheek area circled with dotted line",
    "cheer": "7yo girl, curly red hair, freckles, jumping with arms up, big smile",
    "cheese": "cheese wedge, with holes",
    "cherry": "red cherry, with stem and leaf",
    "chest": "wooden treasure chest, with metal corners",
    "chew": "7yo girl, curly red hair, freckles, chewing, cheeks puffed",
    "chick": "yellow chick, fluffy, small beak",
    "chicken": "white chicken, red comb, standing",
    "chief": "police chief, hat, badge",
    "child": "child, standing, simple",
    "childhood": "7yo girl, curly red hair, freckles, playing with toy blocks",
    "children": "group of children, holding hands, simple",
    "chill": "7yo girl, curly red hair, freckles, relaxed, leaning back",
    "chilly": "7yo girl, curly red hair, freckles, hugging self, visible breath cloud",
    "chimney": "chimney, smoke rising, simple",
    "chin": "face, chin circled, simple",
    "china": "map of China, simple outline",
    "chip": "potato chip, with ridges and salt",
    "chipmunk": "chipmunk, with stripes and bushy tail",
    "chocolate": "chocolate bar, with squares visible",
    "choice": "7yo girl, curly red hair, freckles, pointing at two different items",
    "choose": "7yo girl, curly red hair, freckles, reaching for one item from several",
    "chop": "7yo girl, curly red hair, freckles, holding knife, chopping vegetables",
    "chorus": "7yo girl, curly red hair, freckles, singing with other children in background",
    "chose": "7yo girl, curly red hair, freckles, holding one item, others visible behind",
    "chosen": "7yo girl, curly red hair, freckles, holding star, smiling proudly",
    "christen": "7yo girl, curly red hair, freckles, holding baby in christening gown, priest in background",
    "christmas": "Christmas tree, star on top, ornaments",
    "church": "church, cross on steeple, simple windows",
    "churn": "butter churn, wooden, handle on top",
    "cigarette": "cigarette, lit, smoke rising",
    "circle": "circle, perfect, no details",
    "circus": "circus tent, red and white stripes, flags on top",
    "citizen": "7yo girl, curly red hair, freckles, holding small flag",
    "city": "city skyline, few buildings, windows",
    "clang": "bell, mallet hitting it",
    "clap": "7yo girl, curly red hair, freckles, hands clapping",
    "class": "group of children, sitting at desks",
    "classmate": "7yo girl, curly red hair, freckles, sitting next to another child",
    "classroom": "classroom, desks, chalkboard, teacher's desk",
    "claw": "paw, sharp claws visible",
    "clay": "lump of clay, rough texture, earthy brown",
    "clean": "7yo girl, curly red hair, freckles, wiping table with cloth, surface shiny",
    "cleaner": "spray bottle, blue liquid, trigger handle",
    "clear": "7yo girl, curly red hair, freckles, looking through empty glass frame, background visible",
    "clerk": "person behind counter, name tag, pen and papers",
    "clever": "7yo girl, curly red hair, freckles, solving puzzle, lightbulb above head",
    "click": "7yo girl, curly red hair, freckles, pressing computer mouse button, click icon",
    "cliff": "steep rock face, vertical drop, birds flying nearby",
    "climb": "7yo girl, curly red hair, freckles, climbing ladder",
    "clip": "paper clip, metal, bent",
    "cloak": "cloak, long, with hood",
    "clock": "wall clock, round, with hands and numbers",
    "close": "7yo girl, curly red hair, freckles, closing door",
    "closet": "closet, standing, with doors",
    "cloth": "cloth, square, folded",
    "clothes": "pile of clothes, t-shirt, pants, socks",
    "clothing": "t-shirt, short sleeves",
    "cloud": "fluffy cloud, simple shape",
    "cloudy": "7yo girl, curly red hair, freckles, looking up, cloudy sky",
    "clover": "clover leaf, three leaves",
    "clown": "clown, red nose, colorful wig",
    "club": "golf club, simple shape",
    "cluck": "7yo girl, curly red hair, freckles, mouth open, imitating chicken",
    "clump": "clump of grass, simple shape",
    "coach": "coach, large bus with windows and wheels",
    "coal": "chunk of black coal, rough texture",
    "coast": "coastline, sand meeting water",
    "coat": "coat, buttons and collar visible",
    "cob": "corn cob, kernels visible",
    "cobbler": "cobbler, working on shoe with tools",
    "cocoa": "mug of cocoa, steam rising",
    "coconut": "coconut, whole with husk",
    "cocoon": "cocoon, hanging from branch",
    "cod": "cod fish, side view",
    "codfish": "codfish, whole body",
    "coffee": "steaming coffee cup, handle",
    "coffeepot": "coffeepot, spout and handle",
    "coin": "coin, side view",
    "cold": "7yo girl, curly red hair, freckles, hugging self, visible breath cloud",
    "collar": "shirt collar, folded, buttons",
    "college": "college building, columns, sign",
    "color": "7yo girl, curly red hair, freckles, holding paint palette, splotches visible",
    "colored": "7yo girl, curly red hair, freckles, holding colored pencils, drawing visible",
    "colt": "colt, young horse, standing",
    "column": "column, simple, vertical",
    "comb": "comb, teeth visible",
    "come": "7yo girl, curly red hair, freckles, walking toward viewer, arms open",
    "comfort": "7yo girl, curly red hair, freckles, sitting in cozy chair, blanket visible",
    "comic": "comic book, bold title on cover",
    "coming": "7yo girl, curly red hair, freckles, walking toward viewer, waving",
    "company": "7yo girl, curly red hair, freckles, sitting with group of friends, smiling",
    "compare": "7yo girl, curly red hair, freckles, holding apple in one hand, orange in other, looking between them",
    "conductor": "conductor, black suit, white gloves, baton raised",
    "cone": "ice cream cone, scoop of ice cream on top",
    "connect": "7yo girl, curly red hair, freckles, connecting two puzzle pieces",
    "coo": "dove, open beak, sound waves around head",
    "cook": "7yo girl, curly red hair, freckles, stirring pot on stove",
    "cooked": "7yo girl, curly red hair, freckles, holding plate of spaghetti",
    "cookie": "chocolate chip cookie, round, with chips",
    "cookies": "pile of chocolate chip cookies, stacked",
    "cooking": "7yo girl, curly red hair, freckles, flipping pancake in pan",
    "cool": "7yo girl, curly red hair, freckles, wearing sunglasses, thumbs up",
    "cooler": "cooler, red, with ice and soda cans visible",
    "coop": "wooden chicken coop, with chicken peeking out",
    "copper": "copper metal, reddish-brown, shiny surface",
    "copy": "7yo girl, curly red hair, freckles, holding two identical apples",
    "cord": "braided cord, thick, with texture",
    "cork": "cork bottle stopper, textured surface",
    "corn": "ear of corn, yellow kernels, green husk",
    "corner": "corner where two walls meet, 90-degree angle",
    "correct": "7yo girl, curly red hair, freckles, pointing at checkmark",
    "cost": "7yo girl, curly red hair, freckles, holding price tag with dollar sign",
    "cot": "cot, simple metal frame, thin mattress",
    "cottage": "cottage, small house, chimney, door",
    "cotton": "cotton, fluffy ball, soft texture",
    "couch": "couch, sofa, cushions, armrests",
    "cough": "7yo girl, curly red hair, freckles, coughing, hand over mouth",
    "could": "7yo girl, curly red hair, freckles, thinking, lightbulb above head",
    "couldn't": "7yo girl, curly red hair, freckles, shaking head, frustrated",
    "count": "7yo girl, curly red hair, freckles, counting on fingers, numbers visible",
    "counter": "kitchen counter, visible surface",
    "country": "7yo girl, curly red hair, freckles, holding a flag",
    "county": "7yo girl, curly red hair, freckles, pointing at map",
    "course": "plate with food",
    "court": "basketball court, hoop visible",
    "cousin": "7yo girl, curly red hair, freckles, with another child",
    "cover": "book, cover visible",
    "cow": "cow, spots and horns",
    "coward": "7yo girl, curly red hair, freckles, hiding behind hands, large shadow looming behind",
    "cowardly": "7yo girl, curly red hair, freckles, trembling, knees shaking",
    "cowboy": "cowboy, wide-brimmed hat, lasso in hand",
    "cozy": "7yo girl, curly red hair, freckles, smiling, wrapped in blanket nest",
    "crab": "crab, with claws and legs, facing forward",
    "crack": "crack, in wall, jagged line",
    "cracker": "stack of crackers, square shape, salt crystals visible",
    "cradle": "cradle, rocking, baby inside, hanging from frame",
    "cramps": "7yo girl, curly red hair, freckles, holding stomach, cramp lines visible",
    "cranberry": "cranberries, cluster, round, red",
    "crank": "hand crank, handle, metal",
    "cranky": "7yo girl, curly red hair, freckles, arms crossed, frown",
    "crash": "7yo girl, curly red hair, freckles, toy car crashing into wall",
    "crawl": "7yo girl, curly red hair, freckles, crawling on hands and knees",
    "crazy": "7yo girl, curly red hair, freckles, wild hair, wide eyes, tongue out",
    "cream": "dollop of cream, spoon, white",
    "creamy": "glass of milk, visible cream layer on top",
    "creek": "narrow stream, stones, gentle flow",
    "creep": "7yo girl, curly red hair, freckles, creeping forward on hands and knees",
    "crept": "7yo girl, curly red hair, freckles, having crept, looking back",
    "cried": "7yo girl, curly red hair, freckles, with tears, sad expression",
    "cries": "7yo girl, curly red hair, freckles, crying, tears, open mouth",
    "croak": "frog, open mouth, making sound",
    "crook": "shepherd's crook, curved end",
    "crooked": "7yo girl, curly red hair, freckles, holding crooked stick",
    "crop": "wheat crop, golden stalks with grains",
    "cross": "wooden cross, simple design",
    "cross-eyed": "7yo girl, curly red hair, freckles, cross-eyed, looking at nose",
    "crossing": "pedestrian crossing, white stripes on road",
    "crow": "black crow, perched on branch",
    "crowd": "crowd of people, standing close",
    "crowded": "7yo girl, curly red hair, freckles, in crowded room, people everywhere",
    "crown": "crown, golden, with jewels",
    "cruel": "7yo girl, curly red hair, freckles, frowning, pulling doll's arm",
    "crumb": "bread crumb, small, isolated",
    "crumble": "7yo girl, curly red hair, freckles, crumbling cookie",
    "crush": "7yo girl, curly red hair, freckles, crushing soda can",
    "crust": "bread slice, showing crust edge",
    "cry": "7yo girl, curly red hair, freckles, crying, tears on cheeks",
    "cub": "bear cub, sitting, small",
    "cuff": "shirt cuff, buttons visible",
    "cup": "cup, handle visible",
    "cupboard": "cupboard, doors slightly open",
    "cupful": "cup, filled to brim with liquid",
    "cure": "7yo girl, curly red hair, freckles, holding medicine bottle with cross",
    "curl": "single curly lock of hair",
    "curly": "7yo girl, curly red hair, freckles, smiling",
    "curtain": "curtain, folds visible",
    "curve": "curved road, simple bend",
    "cushion": "cushion, soft fabric, tassels",
    "custard": "bowl of yellow custard, spoon",
    "customer": "7yo girl, curly red hair, freckles, holding shopping bag at counter",
    "cut": "scissors cutting paper, visible cut line",
    "cute": "7yo girl, curly red hair, freckles, smiling, hugging teddy bear",
    "cutting": "knife cutting carrot, visible slice",
    "dab": "7yo girl, curly red hair, freckles, doing dab dance move",
    "dad": "man, short hair, mustache, wearing tie",
    "daddy": "man, smiling, holding child's hand",
    "daily": "7yo girl, curly red hair, freckles, brushing teeth, toothbrush visible",
    "dairy": "milk carton, with cow illustration",
    "daisy": "daisy, white petals, yellow center",
    "dam": "dam, water flowing on one side, dry on other",
    "damage": "7yo girl, curly red hair, freckles, looking at broken toy, toy pieces visible",
    "dame": "woman, wearing elegant dress, holding purse",
    "damp": "7yo girl, curly red hair, freckles, touching damp surface, water droplets visible",
    "dance": "7yo girl, curly red hair, freckles, dancing, arms raised",
    "dancer": "7yo girl, curly red hair, freckles, dancing pose, tutu visible",
    "dancing": "7yo girl, curly red hair, freckles, mid-dance, one leg lifted",
    "dandy": "7yo girl, curly red hair, freckles, wearing fancy suit, top hat",
    "danger": "7yo girl, curly red hair, freckles, wide eyes, danger sign in background",
    "dangerous": "7yo girl, curly red hair, freckles, backing away, sharp object visible",
    "dare": "7yo girl, curly red hair, freckles, pointing forward, determined expression",
    "dark": "dark room, single lamp shining",
    "darkness": "completely black background, small light source",
    "darling": "7yo girl, curly red hair, freckles, hugging teddy bear",
    "darn": "7yo girl, curly red hair, freckles, frustrated, holding broken toy",
    "dart": "dart, pointed tip, feathers",
    "dash": "7yo girl, curly red hair, freckles, running, arms outstretched",
    "date": "date palm fruit, single seed visible",
    "daughter": "young girl, long hair, dress",
    "dawn": "7yo girl, curly red hair, freckles, watching sunrise, sun peeking over horizon",
    "day": "sun in clear sky, simple rays",
    "daybreak": "7yo girl, curly red hair, freckles, watching early sunrise, orange sky",
    "daytime": "bright sun, clear blue sky, simple clouds",
    "dead": "7yo girl, curly red hair, freckles, looking at wilted flower, brown petals",
    "deaf": "7yo girl, curly red hair, freckles, hands over ears, confused expression",
    "deal": "7yo girl, curly red hair, freckles, dealing cards, fan of cards in hand",
    "dear": "7yo girl, curly red hair, freckles, hugging teddy bear tightly, loving expression",
    "death": "7yo girl, curly red hair, freckles, placing flower on gravestone",
    "december": "Christmas tree, decorated with ornaments and star",
    "decide": "7yo girl, curly red hair, freckles, pointing at two paths",
    "deck": "ship deck, wooden, with railing",
    "deed": "certificate, rolled with ribbon",
    "deep": "well, circular, looking down into darkness",
    "deer": "deer, standing, antlers visible",
    "defeat": "7yo girl, curly red hair, freckles, sitting at game board, pieces scattered",
    "defend": "7yo girl, curly red hair, freckles, holding shield, sword ready",
    "defense": "7yo girl, curly red hair, freckles, wearing helmet, holding shield",
    "delight": "7yo girl, curly red hair, freckles, jumping with arms up, confetti falling",
    "den": "animal den, round entrance, leaves around",
    "dentist": "dentist, mask, mirror tool, chair",
    "depend": "7yo girl, curly red hair, freckles, holding rope, leaning on friend",
    "deposit": "piggy bank, coin dropping in slot",
    "describe": "7yo girl, curly red hair, freckles, pointing at picture, talking",
    "desert": "sand dune, cactus",
    "deserve": "7yo girl, curly red hair, freckles, smiling proudly, medal visible",
    "desire": "7yo girl, curly red hair, freckles, reaching out, heart floating above",
    "desk": "desk, pencil, paper",
    "destroy": "7yo girl, curly red hair, freckles, smashing toy, pieces flying",
    "devil": "devil, horns, tail",
    "dew": "leaf, dewdrops",
    "diamond": "diamond, facets",
    "did": "7yo girl, curly red hair, freckles, pointing at calendar with yesterday marked",
    "didn't": "7yo girl, curly red hair, freckles, shaking head, arms crossed",
    "die": "7yo girl, curly red hair, freckles, eyes closed, peaceful expression",
    "died": "7yo girl, curly red hair, freckles, eyes closed, flower on chest",
    "dies": "7yo girl, curly red hair, freckles, eyes closed, wilted flower",
    "difference": "7yo girl, curly red hair, freckles, holding apple and orange side by side",
    "different": "7yo girl, curly red hair, freckles, pointing at red and blue ball",
    "dig": "7yo girl, curly red hair, freckles, digging with shovel, dirt flying",
    "dim": "7yo girl, curly red hair, freckles, squinting, lamp with low light",
    "dime": "dime, showing Roosevelt's profile",
    "dine": "7yo girl, curly red hair, freckles, sitting at table, fork and knife",
    "ding-dong": "doorbell button, sound waves around",
    "dinner": "plate with meat, vegetables, and bread",
    "dip": "7yo girl, curly red hair, freckles, dipping chip in sauce",
    "direct": "7yo girl, curly red hair, freckles, pointing straight ahead",
    "direction": "compass, needle pointing north",
    "dirt": "pile of brown dirt, with small pebbles",
    "dirty": "7yo girl, curly red hair, freckles, dirty hands and face, mud stains",
    "discover": "7yo girl, curly red hair, freckles, looking through magnifying glass, bug visible",
    "dish": "empty plate, with fork and spoon",
    "dislike": "7yo girl, curly red hair, freckles, making disgusted face, broccoli visible",
    "dismiss": "7yo girl, curly red hair, freckles, waving hand dismissively",
    "ditch": "narrow ditch, with water flowing, grassy edges",
    "dive": "7yo girl, curly red hair, freckles, diving into pool, arms extended forward",
    "diver": "diver, full diving gear, oxygen tank",
    "divide": "7yo girl, curly red hair, freckles, using divider tool to split circle",
    "do": "7yo girl, curly red hair, freckles, drawing with crayons",
    "dock": "wooden dock, water visible",
    "doctor": "doctor, white coat, stethoscope",
    "does": "7yo girl, curly red hair, freckles, building with blocks",
    "doesn't": "7yo girl, curly red hair, freckles, shaking head, crossed-out cookie",
    "dog": "dog, friendly, collar",
    "doll": "doll, with dress and hair",
    "dollar": "dollar bill, '$' symbol visible",
    "dolly": "dolly, with wheels and handle",
    "don't": "7yo girl, curly red hair, freckles, shaking head no, red X visible",
    "done": "7yo girl, curly red hair, freckles, thumbs up, checkmark visible",
    "donkey": "donkey, long ears, tail",
    "door": "door, with handle and frame",
    "doorbell": "doorbell button, bell icon visible",
    "doorknob": "doorknob, round, with keyhole",
    "doorstep": "doorstep, single step, in front of door",
    "dope": "7yo girl, curly red hair, freckles, giving thumbs up",
    "dot": "dot, large, black",
    "double": "7yo girl, curly red hair, freckles, holding two identical apples",
    "dough": "dough, ball, with flour",
    "dove": "dove, white, with olive branch",
    "down": "7yo girl, curly red hair, freckles, pointing down with arrow",
    "downstairs": "staircase, descending, arrow pointing down",
    "downtown": "cityscape, tall buildings, busy street",
    "dozen": "12 eggs in carton",
    "drag": "7yo girl, curly red hair, freckles, dragging heavy suitcase",
    "drain": "sink drain, water swirling down",
    "drank": "7yo girl, curly red hair, freckles, drinking from straw",
    "draw": "7yo girl, curly red hair, freckles, drawing with crayons",
    "drawer": "open drawer, socks visible",
    "drawing": "sheet of paper with crayon drawing of house",
    "dream": "7yo girl, curly red hair, freckles, sleeping, thought bubble with castle",
    "dress": "girl's dress with bow, simple silhouette",
    "dresser": "chest of drawers with round handles",
    "dressmaker": "woman holding dress form and scissors",
    "drew": "7yo girl, curly red hair, freckles, drawing house with crayon",
    "dried": "wet clothes hanging on line, now dry",
    "drift": "small boat drifting on calm water",
    "drill": "drill, with drill bit and cord",
    "drink": "7yo girl, curly red hair, freckles, drinking from cup",
    "drip": "7yo girl, curly red hair, freckles, looking up, water drop falling",
    "drive": "7yo girl, curly red hair, freckles, holding steering wheel",
    "driven": "7yo girl, curly red hair, freckles, determined, trophy slightly visible",
    "driver": "person in driver's seat, holding steering wheel",
    "drop": "water drop, with splash",
    "drove": "7yo girl, curly red hair, freckles, in car seat, holding steering wheel",
    "drown": "7yo girl, curly red hair, freckles, arms up, bubbles around, in water",
    "drowsy": "7yo girl, curly red hair, freckles, yawning, eyes half-closed",
    "drub": "7yo girl, curly red hair, freckles, hitting drum with sticks",
    "drum": "drum, with sticks nearby",
    "drunk": "7yo girl, curly red hair, freckles, stumbling, holding bottle",
    "dry": "7yo girl, curly red hair, freckles, touching dry soil, cracked ground visible",
    "duck": "duck, with webbed feet and beak",
    "due": "7yo girl, curly red hair, freckles, holding calendar, pointing at date",
    "dug": "7yo girl, curly red hair, freckles, digging with small shovel, pile of dirt beside",
    "dull": "7yo girl, curly red hair, freckles, yawning, dim lightbulb above",
    "dumb": "7yo girl, curly red hair, freckles, mouth zipped shut, confused expression",
    "dump": "pile of trash, old tires, broken toys, scattered",
    "during": "7yo girl, curly red hair, freckles, eating sandwich, clock showing midday",
    "dust": "small pile of dust, floating particles, simple shape",
    "dusty": "7yo girl, curly red hair, freckles, sneezing, dusty old book in hand",
    "duty": "7yo girl, curly red hair, freckles, making bed, toys on floor",
    "dwarf": "dwarf, short, beard, pointy hat",
    "dwell": "7yo girl, curly red hair, freckles, waving from window of house",
    "dwelt": "7yo girl, curly red hair, freckles, waving from window of house, old clock visible",
    "dying": "7yo girl, curly red hair, freckles, looking sad at wilting flower",
    "each": "7yo girl, curly red hair, freckles, pointing at one apple among many",
    "eager": "7yo girl, curly red hair, freckles, jumping with hands up, big smile",
    "eagle": "eagle, spread wings, sharp beak",
    "ear": "human ear, side view, simple shape",
    "early": "7yo girl, curly red hair, freckles, yawning, sun rising behind",
    "earn": "7yo girl, curly red hair, freckles, holding coins, piggy bank nearby",
    "earth": "Earth globe, blue oceans, green continents, white clouds",
    "east": "7yo girl, curly red hair, freckles, pointing at sun rising, 'E' marked on horizon",
    "eastern": "7yo girl, curly red hair, freckles, pointing at map, eastern region highlighted",
    "easy": "7yo girl, curly red hair, freckles, smiling, stacking blocks effortlessly",
    "eat": "7yo girl, curly red hair, freckles, eating sandwich, crumbs falling",
    "eaten": "7yo girl, curly red hair, freckles, looking at empty plate, crumbs on table",
    "edge": "sharp edge of table, corner visible",
    "egg": "egg, whole, with shell",
    "eh": "7yo girl, curly red hair, freckles, shrugging, question mark above",
    "eight": "number 8, bold, simple",
    "eighteen": "number 18, bold, simple",
    "eighth": "7yo girl, curly red hair, freckles, holding 8th place ribbon",
    "eighty": "number 80, bold, simple",
    "either": "7yo girl, curly red hair, freckles, pointing at two apples",
    "elbow": "human elbow, bent at 90 degrees",
    "elder": "elder tree, clusters of berries",
    "eldest": "7yo girl, curly red hair, freckles, standing next to elderly person",
    "electric": "7yo girl, curly red hair, freckles, hair standing up, lightning bolt in background",
    "electricity": "7yo girl, curly red hair, freckles, hair standing up, lightning bolt in background",
    "elephant": "elephant, large ears, trunk raised",
    "eleven": "number 11, bold, simple sans-serif",
    "elf": "elf, pointed ears, green hat",
    "elm": "elm tree, with serrated leaves",
    "else": "7yo girl, curly red hair, freckles, pointing at two doors",
    "elsewhere": "7yo girl, curly red hair, freckles, pointing away from scene",
    "empty": "7yo girl, curly red hair, freckles, looking surprised at empty box",
    "end": "7yo girl, curly red hair, freckles, standing at end of dotted line",
    "ending": "7yo girl, curly red hair, freckles, holding book with last page showing",
    "enemy": "cartoon villain, angry face, black cape",
    "engine": "car engine, visible pistons and wires",
    "engineer": "engineer, hard hat, holding wrench",
    "english": "7yo girl, curly red hair, freckles, pointing at British flag",
    "enjoy": "7yo girl, curly red hair, freckles, laughing, eating ice cream",
    "enough": "7yo girl, curly red hair, freckles, holding full plate of food",
    "enter": "7yo girl, curly red hair, freckles, opening door, stepping through",
    "envelope": "envelope, with stamp and address visible",
    "equal": "7yo girl, curly red hair, freckles, holding balanced scales",
    "erase": "7yo girl, curly red hair, freckles, erasing chalkboard",
    "eraser": "eraser, pink, rectangular",
    "errand": "7yo girl, curly red hair, freckles, holding shopping bag, store sign slightly visible",
    "escape": "7yo girl, curly red hair, freckles, running, arms outstretched",
    "eve": "7yo girl, curly red hair, freckles, looking at calendar, star marking next day",
    "even": "7yo girl, curly red hair, freckles, smoothing wrinkled paper",
    "evening": "7yo girl, curly red hair, freckles, watching sunset, tree silhouette",
    "ever": "7yo girl, curly red hair, freckles, looking at timeline, question mark",
    "every": "7yo girl, curly red hair, freckles, holding calendar, all days marked",
    "everybody": "7yo girl, curly red hair, freckles, surrounded by diverse children of different ethnicities",
    "everyday": "7yo girl, curly red hair, freckles, brushing teeth at sink",
    "everyone": "7yo girl, curly red hair, freckles, surrounded by diverse children of different ethnicities",
    "everything": "7yo girl, curly red hair, freckles, surrounded by toys, books, and everyday objects",
    "everywhere": "7yo girl, curly red hair, freckles, looking at world map with hands spread wide",
    "evil": "7yo girl, curly red hair, freckles, frowning with arms crossed, looking stern",
    "exact": "7yo girl, curly red hair, freckles, measuring pencil with ruler, focused expression",
    "except": "7yo girl, curly red hair, freckles, pointing at one apple among many fruits",
    "exchange": "7yo girl, curly red hair, freckles, holding out toy, boy receiving it",
    "excited": "7yo girl, curly red hair, freckles, jumping with arms up, wide eyes, big smile",
    "exciting": "7yo girl, curly red hair, freckles, eyes wide, pointing at roller coaster",
    "excuse": "7yo girl, curly red hair, freckles, hands clasped, looking up with apologetic expression",
    "exit": "exit sign, green, with running man and arrow",
    "expect": "7yo girl, curly red hair, freckles, looking up with hands on hips, expectant expression",
    "explain": "7yo girl, curly red hair, freckles, pointing at diagram, talking",
    "extra": "7yo girl, curly red hair, freckles, holding one cookie, plate with extra cookies visible",
    "eye": "human eye, with eyelashes",
    "eyebrow": "human eyebrow, above eye",
    "fable": "7yo girl, curly red hair, freckles, reading book, fox and grapes visible",
    "face": "human face, smiling",
    "facing": "7yo girl, curly red hair, freckles, facing forward",
    "fact": "7yo girl, curly red hair, freckles, holding book, lightbulb above",
    "factory": "factory, with smokestacks",
    "fail": "7yo girl, curly red hair, freckles, looking disappointed, broken toy nearby",
    "faint": "7yo girl, curly red hair, freckles, fainting, eyes closed, body limp",
    "fair": "7yo girl, curly red hair, freckles, holding balanced scales",
    "fairy": "fairy, with wings and wand",
    "faith": "7yo girl, curly red hair, freckles, hands clasped in prayer",
    "fake": "7yo girl, curly red hair, freckles, holding toy flower, real flower visible",
    "fall": "7yo girl, curly red hair, freckles, falling, arms out, hair flying",
    "false": "7yo girl, curly red hair, freckles, shaking head, X mark visible",
    "family": "family of four, parents and two children",
    "fan": "table fan, visible blades, protective cage",
    "fancy": "7yo girl, curly red hair, freckles, admiring fancy decorated birthday cake",
    "far": "7yo girl, curly red hair, freckles, squinting, distant mountains visible",
    "far-off": "7yo girl, curly red hair, freckles, pointing, tiny airplane in distant sky",
    "faraway": "7yo girl, curly red hair, freckles, looking through binoculars, distant ship visible",
    "fare": "bus ticket, visible numbers, simple design",
    "farm": "red barn, silo, simple farm building",
    "farmer": "farmer, straw hat, holding pitchfork",
    "farming": "tractor, plowing field",
    "farther": "7yo girl, curly red hair, freckles, pointing far away",
    "fashion": "dress, stylish design",
    "fast": "7yo girl, curly red hair, freckles, running, hair blowing back",
    "fasten": "7yo girl, curly red hair, freckles, fastening seatbelt",
    "fat": "round, chubby character",
    "father": "man, holding child's hand",
    "fault": "7yo girl, curly red hair, freckles, looking guilty, hands behind back",
    "favor": "7yo girl, curly red hair, freckles, handing small gift to friend",
    "favorite": "7yo girl, curly red hair, freckles, pointing at ice cream cone",
    "fear": "7yo girl, curly red hair, freckles, hiding behind hands, spider visible",
    "feast": "table covered with various dishes, turkey, pies, fruits",
    "feather": "large feather, visible barbs and quill",
    "february": "snowy landscape, bare trees, child building snowman",
    "fed": "7yo girl, curly red hair, freckles, feeding ducks with bread",
    "feed": "7yo girl, curly red hair, freckles, holding bowl of food for dog",
    "feel": "7yo girl, curly red hair, freckles, hands on chest, eyes closed, smiling",
    "feet": "two bare feet, toes visible",
    "fell": "7yo girl, curly red hair, freckles, falling backward, arms out",
    "fellow": "cartoon boy, simple face",
    "felt": "square of fabric, slightly fuzzy",
    "fence": "wooden fence, simple vertical slats",
    "fever": "7yo girl, curly red hair, freckles, thermometer in mouth, flushed cheeks",
    "few": "7yo girl, curly red hair, freckles, holding 2-3 apples",
    "fib": "7yo girl, curly red hair, freckles, crossing fingers behind back",
    "fiddle": "violin with bow, simple shape",
    "field": "grassy field with a few flowers",
    "fife": "simple flute, held horizontally",
    "fifteen": "number 15, bold, simple",
    "fifth": "number 5 with 'th' suffix, bold, simple",
    "fifty": "number 50, bold, simple",
    "fig": "fig, simple shape with stem",
    "fight": "7yo girl, curly red hair, freckles, pushing another child",
    "figure": "simple human figure, stick person style",
    "file": "manila folder, papers sticking out",
    "fill": "7yo girl, curly red hair, freckles, pouring water into cup",
    "film": "movie film reel, tape visible",
    "finally": "7yo girl, curly red hair, freckles, crossing finish line",
    "find": "7yo girl, curly red hair, freckles, holding magnifying glass, treasure chest visible",
    "fine": "7yo girl, curly red hair, freckles, giving thumbs up",
    "finger": "hand, one finger pointing",
    "finish": "7yo girl, curly red hair, freckles, crossing finish line, ribbon breaking",
    "fire": "flames, campfire shape",
    "firearm": "gun, simple shape",
    "firecracker": "firecracker, fuse, sparks flying",
    "fireplace": "fireplace, flames inside",
    "fireworks": "fireworks, colorful explosions in sky",
    "firing": "7yo girl, curly red hair, freckles, shooting gun, smoke",
    "first": "7yo girl, curly red hair, freckles, holding up one finger, ribbon with '1' visible",
    "fish": "fish, fins and tail clearly visible",
    "fisherman": "fisherman, fishing rod, hat, standing by water",
    "fist": "closed fist, fingers curled",
    "fit": "7yo girl, curly red hair, freckles, squeezing into small box",
    "fits": "key, fitting perfectly into lock",
    "five": "number 5, bold, simple sans-serif",
    "fix": "7yo girl, curly red hair, freckles, using wrench on broken toy",
    "flag": "flag, waving on pole",
    "flake": "snowflake, falling",
    "flame": "flame, from candle",
    "flap": "7yo girl, curly red hair, freckles, arms flapping like wings",
    "flash": "7yo girl, curly red hair, freckles, hand flashing light",
    "flashlight": "flashlight, beam of light shining",
    "flat": "flat tire, completely deflated",
    "flea": "flea, jumping on dog",
    "flesh": "raw meat, red, with white fat marbling",
    "flew": "7yo girl, curly red hair, freckles, arms outstretched, flying through air",
    "flies": "housefly, wings spread, compound eyes visible",
    "flight": "7yo girl, curly red hair, freckles, arms outstretched, wind lines around",
    "flip": "7yo girl, curly red hair, freckles, mid-flip, upside down",
    "flip-flop": "pair of flip-flops, thong straps, flat soles",
    "float": "7yo girl, curly red hair, freckles, floating on back, water ripples",
    "flock": "flock of birds, V-formation, wings spread",
    "flood": "house, water up to windows, roof visible",
    "floor": "room corner, floor and wall meeting",
}