words = {

    "a": "single red apple",
    "able": "7yo girl, curly red hair, freckles, lifting heavy barbell with effort",
    "aboard": "7yo girl, curly red hair, freckles, standing on large ship deck",
    "about": "7yo girl, curly red hair, freckles, standing about large tree",
    "above": "7yo girl, curly red hair, freckles, looking up at kite above",
    "absent": "empty classroom chair with 'John' name tag",
    "accept": "7yo girl, curly red hair, freckles, accepting gift box with both hands",
    "accident": "broken toy car with wheels off",
    "account": "pink piggy bank with coins inside",
    "ache": "7yo girl, curly red hair, freckles, holding head with pained expression",
    "aching": "7yo girl, curly red hair, freckles, rubbing sore arm with grimace",
    "acorn": "acorn with cap and stem",
    "acre": "green field with '1 acre' sign",
    "across": "7yo girl, curly red hair, freckles, walking across wooden bridge",
    "act": "7yo girl, curly red hair, freckles, acting on stage with microphone",
    "acts": "7yo girl, curly red hair, freckles, jumping with arms raised",
    "add": "two apples plus one apple equals three apples",
    "address": "envelope with address written on front",
    "admire": "7yo girl, curly red hair, freckles, looking up at rainbow with hands clasped",
    "adventure": "7yo girl, curly red hair, freckles, wearing backpack, holding map, looking excited",
    "afar": "distant mountains, tiny 7yo girl, curly red hair, freckles walking toward them",
    "afraid": "7yo girl, curly red hair, freckles, hiding behind hands, large spider visible",
    "after": "clock showing 2 o'clock, then 3 o'clock",
    "afternoon": "sun high in sky casting short shadows, clock showing 3 o'clock",
    "afterward": "child eating ice cream, then child with empty cone smiling",
    "again": "7yo girl, curly red hair, freckles, jumping, then jumping again",
    "against": "7yo girl, curly red hair, freckles, pushing hands against brick wall",
    "age": "birthday cake with 7 candles, child blowing them out",
    "aged": "7yo girl, curly red hair, freckles, then same girl with gray hair and cane",
    "ago": "old clock showing 3 o'clock, calendar page turning",
    "agree": "two people shaking hands, smiling at each other",
    "ah": "7yo girl, curly red hair, freckles, lightbulb above head, hands on cheeks",
    "ahead": "straight road stretching into distance, mountains in background",
    "aid": "red cross first aid kit, open with bandages visible",
    "aim": "7yo girl, curly red hair, freckles, holding bow, arrow aimed at target",
    "air": "wind blowing tree leaves, swirling motion lines",
    "airfield": "long runway, small airplane taking off, control tower",
    "airplane": "passenger airplane flying, wings visible, contrail behind",
    "airport": "airport terminal building, airplane parked at gate, control tower",
    "airship": "large airship floating, propellers visible, sky background",
    "airy": "large open room, tall windows, curtains blowing in breeze",
    "alarm": "alarm clock ringing, bells swinging, hands at 7 o'clock",
    "alike": "two identical teddy bears, side by side, same size",
    "alive": "7yo girl, curly red hair, freckles, jumping high, arms spread, smiling",
    "all": "pile of colorful balloons, all floating",
    "alley": "narrow alley between brick buildings, with lampposts",
    "alligator": "alligator with open mouth, sharp teeth visible",
    "allow": "7yo girl, curly red hair, freckles, giving thumbs up",
    "almost": "15yo girl, curly red hair, freckles, teen style, reaching for apple on tree branch",
    "alone": "single red balloon floating on white background",
    "along": "7yo girl, curly red hair, freckles, walking along garden path",
    "aloud": "15yo girl, curly red hair, freckles, teen style, speaking with speech bubble",
    "already": "25yo woman, curly red hair, freckles, adult style, checking off completed list",
    "also": "pile of books, also with pencils scattered around",
    "always": "pattern of stars, always repeating in night sky",
    "am": "7yo girl, curly red hair, freckles, pointing to herself",
    "america": "map outline of North America, with stars and stripes",
    "american": "american flag waving in wind",
    "among": "25yo woman, curly red hair, freckles, adult style, standing among group of people",
    "amount": "pile of gold coins, some stacked high",
    "an": "apple with leaf",
    "and": "red apple and green pear side by side",
    "angel": "angel with wings and halo, holding a harp",
    "anger": "15yo girl, curly red hair, freckles, clenching fists, teeth gritted",
    "angry": "15yo girl, curly red hair, freckles, stomping foot, arms crossed, scowling",
    "animal": "brown dog sitting, tail wagging",
    "another": "second red apple next to first",
    "answer": "15yo girl, curly red hair, freckles, raising hand confidently",
    "ant": "ant carrying leaf, walking on ground",
    "any": "red apple, green pear, yellow banana in a row",
    "anybody": "silhouette of person standing",
    "anyhow": "15yo girl, curly red hair, freckles, shrugging shoulders, palms up",
    "anyone": "generic person icon, simple stick figure",
    "anything": "red apple, green pear, yellow banana, blue ball in a row",
    "anyway": "7yo girl, curly red hair, freckles, shrugging shoulders, palms up",
    "anywhere": "7yo girl, curly red hair, freckles, pointing at world map, excited",
    "apart": "two apples, apart with gap between them",
    "apartment": "apartment building with windows and balcony",
    "ape": "gorilla sitting on ground, arms folded",
    "apiece": "three apples, each on separate plate",
    "appear": "7yo girl, curly red hair, freckles, popping out from behind curtain",
    "apple": "apple, with leaf and stem",
    "april": "calendar page showing April, with flowers",
    "apron": "chef wearing white apron, holding wooden spoon",
    "are": "three apples, arranged in row",
    "aren't": "two apples, crossed out with red X",
    "arise": "sun rising over horizon, with rays",
    "arithmetic": "chalkboard with arithmetic problem: 2+2=4",
    "arm": "human arm with hand, pointing finger",
    "armful": "7yo girl, curly red hair, freckles, arms full of colorful flowers",
    "army": "line of soldiers in formation, helmets and rifles",
    "arose": "sun rising over mountains, orange sky",
    "around": "7yo girl, curly red hair, freckles, circling a large tree",
    "arrange": "7yo girl, curly red hair, freckles, arranging books on shelf",
    "arrive": "7yo girl, curly red hair, freckles, arriving at school bus stop",
    "arrived": "7yo girl, curly red hair, freckles, standing at school entrance",
    "arrow": "arrow with feathers, pointing right",
    "art": "paintbrushes, palette, colorful paints on easel",
    "artist": "7yo girl, curly red hair, freckles, painting on canvas with brush",
    "as": "7yo girl, curly red hair, freckles, jumping as high as her friend",
    "ash": "pile of gray ash from fireplace",
    "ashes": "multiple piles of gray ash from campfire",
    "aside": "7yo girl, curly red hair, freckles, pushing box aside",
    "ask": "7yo girl, curly red hair, freckles, raising hand to ask teacher",
    "asleep": "7yo girl, curly red hair, freckles, sleeping peacefully, eyes closed, hugging teddy bear",
    "at": "7yo girl, curly red hair, freckles, standing at bus stop, waiting",
    "ate": "7yo girl, curly red hair, freckles, eating apple, smiling",
    "attack": "7yo girl, curly red hair, freckles, defending with shield against dragon",
    "attend": "7yo girl, curly red hair, freckles, attending school, raising hand in class",
    "attention": "7yo girl, curly red hair, freckles, paying attention, eyes wide, finger pointing",
    "august": "calendar page showing August, with beach scene",
    "aunt": "woman hugging 7yo girl, curly red hair, freckles, smiling",
    "author": "woman writing in notebook at desk",
    "auto": "red car, with wheels and windows",
    "automobile": "blue car, with wheels and windows",
    "autumn": "fall scene with orange leaves, pumpkin, and scarecrow",
    "avenue": "wide avenue with tall buildings and trees",
    "awake": "7yo girl, curly red hair, freckles, waking up, stretching arms",
    "awaken": "7yo girl, curly red hair, freckles, gently waking brother, shaking shoulder",
    "away": "7yo girl, curly red hair, freckles, walking away into distance",
    "awful": "7yo girl, curly red hair, freckles, pinching nose, face scrunched in disgust",
    "awfully": "7yo girl, curly red hair, freckles, holding nose, face twisted in extreme disgust",
    "awhile": "7yo girl, curly red hair, freckles, sitting on floor, looking at watch, waiting",
    "ax": "wood-cutting axe with wooden handle",
    "axe": "wood-cutting axe with wooden handle",
    "baa": "sheep with open mouth, making baa sound",
    "babe": "cute baby with pacifier, smiling",
    "babies": "group of babies crawling on floor",
    "back": "person from behind, back view",
    "background": "blurred background, sharp tree in foreground",
    "backward": "7yo girl, curly red hair, freckles, walking backward, looking over shoulder",
    "backwards": "7yo girl, curly red hair, freckles, walking backward, looking over shoulder",
    "bacon": "crispy bacon strips on plate",
    "bad": "7yo girl, curly red hair, freckles, giving thumbs down, frowning",
    "badge": "police badge, silver star with eagle emblem",
    "badly": "7yo girl, curly red hair, freckles, frowning, thumbs down",
    "bag": "canvas backpack, blue with zipper",
    "bake": "7yo girl, curly red hair, freckles, wearing oven mitts, taking tray from oven",
    "baker": "baker in white uniform, holding fresh bread loaf",
    "bakery": "bakery shop window, bread loaves and pastries on display",
    "baking": "oven with open door, baking tray with cookies inside",
    "ball": "soccer ball, black and white pattern",
    "balloon": "red helium balloon, floating with string",
    "banana": "yellow banana, peeled with curved shape",
    "band": "rock band on stage, guitars and drums",
    "bandage": "rolled white bandage, medical gauze",
    "bang": "7yo girl, curly red hair, freckles, covering ears, shocked expression",
    "banjo": "banjo, round body with strings and fretboard",
    "bank": "bank building, columns and ATM machine outside",
    "banker": "banker in suit, holding briefcase",
    "barber": "barber with scissors and comb",
    "bare": "tree trunk bare of leaves",
    "barefoot": "feet barefoot on grass",
    "barely": "7yo girl, curly red hair, freckles, squeezing through narrow gap, barely fitting",
    "bark": "tree bark texture",
    "barn": "red barn with hayloft",
    "barrel": "wooden barrel with metal bands",
    "base": "baseball base on field",
    "baseball": "baseball with red stitching",
    "basement": "basement with stairs and concrete walls",
    "basket": "wicker basket with handle",
    "bat": "baseball bat with grip tape",
    "batch": "batch of cookies on baking sheet",
    "bath": "bathtub filled with water, bubbles",
    "bathe": "7yo girl, curly red hair, freckles, washing hair in bathtub, soap bubbles",
    "bathing": "7yo girl, curly red hair, freckles, bathing in bathtub, splashing water",
    "bathroom": "bathroom with bathtub, sink, and toilet",
    "bathtub": "bathtub with water and bubbles",
    "battle": "soldiers in battle, swords clashing",
    "battleship": "battleship sailing on ocean",
    "bay": "bay with calm water and surrounding land",
    "be": "7yo girl, curly red hair, freckles, simply existing, standing calmly",
    "beach": "beach with sand, waves, and palm trees",
    "bead": "string of colorful beads",
    "beam": "wooden beam supporting ceiling",
    "bean": "green bean pod with seeds",
    "bear": "brown bear standing on hind legs",
    "beard": "man with long, bushy beard",
    "beast": "fierce lion roaring, sharp teeth, mane",
    "beat": "drummer hitting drum with sticks, rhythm",
    "beating": "heart beating, red heart with motion lines",
    "beautiful": "rose in full bloom, petals open, green stem",
    "beautify": "gardener planting colorful flowers in garden",
    "beauty": "butterfly with colorful wings, orange and blue",
    "became": "caterpillar transforming into butterfly, wings emerging",
    "because": "rain falling, person opening umbrella, cause and effect",
    "become": "seed sprouting, growing into green plant with leaves",
    "becoming": "butterfly emerging from cocoon, wings unfolding",
    "bed": "simple wooden bed frame with mattress",
    "bedbug": "bedbug crawling on white mattress, small brown insect",
    "bedroom": "bedroom with bed, window, and curtains",
    "bedspread": "colorful bedspread on bed, floral pattern",
    "bedtime": "child sleeping in bed, moon visible through window",
    "bee": "bee, yellow and black stripes, wings spread",
    "beech": "beech tree, smooth gray bark, green leaves",
    "beef": "raw beef steak, marbled meat",
    "beefsteak": "grilled beefsteak, grill marks, sizzling",
    "beehive": "beehive, wooden structure, bees flying around",
    "been": "7yo girl, curly red hair, freckles, holding completed checklist",
    "beet": "beet, deep red root, green leaves attached",
    "before": "clock showing 3 o'clock, 7yo girl, curly red hair, freckles pointing at it",
    "beg": "7yo girl, curly red hair, freckles, kneeling, hands clasped, pleading",
    "began": "7yo girl, curly red hair, freckles, crouching to start race",
    "beggar": "person sitting on street, holding cup, cardboard sign",
    "begged": "7yo girl, curly red hair, freckles, kneeling, hands clasped, tears in eyes",
    "begin": "7yo girl, curly red hair, freckles, crouching at starting line",
    "beginning": "7yo girl, curly red hair, freckles, standing at start of path",
    "begun": "7yo girl, curly red hair, freckles, holding paintbrush, painting canvas",
    "behave": "7yo girl, curly red hair, freckles, sitting straight, hands folded, smiling politely",
    "behind": "MASSIVE oak tree filling frame, tiny 7yo girl, curly red hair, freckles peeking from behind trunk",
    "being": "7yo girl, curly red hair, freckles, sitting peacefully on grass",
    "believe": "7yo girl, curly red hair, freckles, hands together, eyes closed, smiling",
    "bell": "school bell with rope, mounted on wall",
    "belong": "7yo girl, curly red hair, freckles, sitting with friends in circle",
    "below": "kite flying high, string leading to 7yo girl, curly red hair, freckles holding it below",
    "belt": "leather belt with metal buckle",
    "bench": "wooden park bench with backrest",
    "bend": "7yo girl, curly red hair, freckles, bending over to tie shoe",
    "beneath": "bridge arching over river, boat floating beneath",
    "bent": "7yo girl, curly red hair, freckles, bent over tying shoe",
    "berries": "bowl of mixed berries: strawberries, blueberries, raspberries",
    "berry": "single red strawberry with green stem and leaves",
    "beside": "TINY 7yo girl, curly red hair, freckles, standing beside large tree",
    "besides": "7yo girl, curly red hair, freckles, holding apple, besides banana and orange",
    "best": "7yo girl, curly red hair, freckles, holding gold trophy, smiling proudly",
    "bet": "15yo girl, curly red hair, freckles, teen style, holding playing cards",
    "better": "7yo girl, curly red hair, freckles, choosing bigger apple over smaller one",
    "between": "TINY 7yo girl, curly red hair, freckles, standing between two large trees",
    "bib": "baby wearing colorful bib, eating",
    "bible": "open bible with cross on cover",
    "bicycle": "child riding red bicycle with training wheels",
    "bid": "15yo girl, curly red hair, freckles, teen style, raising hand at auction",
    "big": "GIANT teddy bear, tiny 7yo girl, curly red hair, freckles hugging its leg",
    "bigger": "GIANT teddy bear, tiny 7yo girl, curly red hair, freckles, next to smaller teddy bear",
    "bill": "dollar bill with George Washington",
    "billboard": "large billboard with colorful advertisement",
    "bin": "blue recycling bin with paper inside",
    "bind": "7yo girl, curly red hair, freckles, tying rope around box",
    "bird": "sparrow on branch, wings spread",
    "birth": "newborn baby in blanket, tiny hands visible",
    "birthday": "birthday cake with 5 candles, colorful frosting",
    "biscuit": "round biscuit with chocolate chips, slightly golden",
    "bit": "small piece of apple, bite-sized",
    "bite": "7yo girl, curly red hair, freckles, biting red apple",
    "biting": "7yo girl, curly red hair, freckles, biting sandwich, teeth visible",
    "bitter": "7yo girl, curly red hair, freckles, tasting lemon, face scrunched",
    "black": "black cat, sitting, yellow eyes",
    "blackberry": "cluster of blackberries, deep purple, on bush",
    "blackbird": "blackbird on wooden fence, yellow beak",
    "blackboard": "blackboard with white chalk writing, wooden frame",
    "blackness": "dark room, single candle flame, shadows everywhere",
    "blacksmith": "blacksmith hammering red-hot metal on anvil, sparks flying",
    "blame": "7yo girl, curly red hair, freckles, pointing at broken vase, looking guilty",
    "blank": "blank sheet of paper, no writing",
    "blanket": "folded blanket on bed, soft texture",
    "blast": "wind blowing leaves off tree, strong gust",
    "blaze": "large campfire flames, bright orange and yellow",
    "bleed": "cut finger with small blood drops, medical bandage nearby",
    "bless": "hands together in prayer, gentle light rays",
    "blessing": "7yo girl, curly red hair, freckles, receiving gift box with bow",
    "blew": "dandelion seeds flying in wind, some still attached",
    "blind": "window blinds, half-open, casting shadows",
    "blindfold": "7yo girl, curly red hair, freckles, wearing black blindfold",
    "blinds": "vertical blinds on window, sunlight filtering through",
    "block": "wooden building block, alphabet letter A on side",
    "blood": "single red blood drop, medical context",
    "bloom": "rose flower blooming, petals opening",
    "blossom": "cherry blossom branch with pink flowers",
    "blot": "ink blot spreading on white paper",
    "blow": "7yo girl, curly red hair, freckles, blowing soap bubbles",
    "blue": "clear blue sky with fluffy white clouds",
    "blueberry": "handful of fresh blueberries",
    "bluebird": "bluebird perched on flowering branch",
    "blush": "7yo girl, curly red hair, freckles, cheeks bright red, looking down shyly",
    "board": "wooden chalkboard with wooden frame",
    "boast": "7yo girl, curly red hair, freckles, flexing arm muscles, grinning proudly",
    "boat": "small sailboat with white sails on calm water",
    "bob": "7yo girl, curly red hair, freckles, bobbing head to music",
    "bobwhite": "bobwhite quail standing in tall grass",
    "bodies": "group of diverse cartoon bodies in different poses",
    "body": "simple cartoon body outline with arms and legs",
    "boil": "pot of water boiling with steam rising",
    "boiler": "metal boiler with pipes and pressure gauge",
    "bold": "7yo girl, curly red hair, freckles, hands on hips, chin up, confident smile",
    "bone": "dog bone, raw beef bone with marrow",
    "bonnet": "traditional bonnet with ribbon ties",
    "boo": "7yo girl, curly red hair, freckles, hands up, mouth open saying 'boo!'",
    "book": "open book with visible pages and bookmark",
    "bookcase": "wooden bookcase filled with colorful books",
    "bookkeeper": "woman in glasses with calculator and ledger book",
    "boom": "explosion with smoke cloud and 'BOOM!' sound effect",
    "boot": "work boot with laces and thick sole",
    "born": "baby being held by doctor, umbilical cord visible",
    "borrow": "7yo girl, curly red hair, freckles, handing pencil to friend",
    "boss": "woman in suit pointing at chart, authoritative pose",
    "both": "two apples side by side, both red and shiny",
    "bother": "7yo girl, curly red hair, freckles, covering ears, annoyed expression",
    "bottle": "plastic water bottle with blue cap",
    "bottom": "7yo girl, curly red hair, freckles, standing at bottom of stairs",
    "bought": "7yo girl, curly red hair, freckles, holding shopping bag with bread",
    "bounce": "red rubber ball bouncing high",
    "bow": "pink hair bow with polka dots",
    "bow-wow": "brown dog with tongue out, barking",
    "bowl": "white ceramic bowl",
    "box": "brown cardboard box with flaps open",
    "boxcar": "red boxcar on train tracks",
    "boxer": "brown boxer dog with short coat",
    "boxes": "stack of three cardboard boxes",
    "boy": "7yo boy, curly red hair, freckles, playing with toy car",
    "boyhood": "7yo boy, curly red hair, freckles, climbing tree",
    "bracelet": "silver charm bracelet on wrist",
    "brain": "human brain with labeled parts",
    "brake": "car brake pedal, metal and rubber",
    "bran": "bowl of wheat bran, brown flakes",
    "branch": "tree branch with green leaves",
    "brass": "brass trumpet, shiny golden metal",
    "brave": "7yo girl, curly red hair, freckles, standing tall, chest out, smiling confidently",
    "bread": "loaf of bread, golden crust, sliced",
    "break": "7yo girl, curly red hair, freckles, breaking wooden stick over knee",
    "breakfast": "breakfast plate with fried eggs, toast, and orange juice",
    "breast": "bird's breast feathers, colorful pattern",
    "breath": "7yo girl, curly red hair, freckles, breathing out cold air in winter, visible steam",
    "breathe": "7yo girl, curly red hair, freckles, taking deep breath, hands on chest",
    "breeze": "tree branches swaying gently in breeze, leaves rustling",
    "brick": "red clay brick, rectangular shape",
    "bride": "bride in white wedding dress, veil, holding bouquet",
    "bridge": "stone bridge over river, arches, water flowing",
    "bright": "sun shining on yellow flower, bright light",
    "brightness": "desk lamp with bright light bulb, shining",
    "bring": "7yo girl, curly red hair, freckles, carrying book in hands",
    "broad": "WIDE river flowing between mountains, boat on water",
    "broadcast": "radio tower with signal waves, broadcasting",
    "broke": "7yo girl, curly red hair, freckles, holding broken toy car",
    "broken": "cracked ceramic vase with pieces on floor",
    "brook": "clear brook flowing over smooth stones, forest",
    "broom": "wooden broom with straw bristles, leaning against wall",
    "brother": "two boys, older and younger, playing together",
    "brought": "7yo girl, curly red hair, freckles, carrying basket of apples",
    "brown": "brown bear standing on all fours, forest",
    "brush": "paintbrush with blue paint on bristles, canvas",
    "bubble": "soap bubble floating in air, rainbow colors",
    "bucket": "metal bucket with handle, sitting on ground",
    "buckle": "metal belt buckle with prong",
    "bud": "rose bud, tightly closed",
    "buffalo": "American bison, shaggy brown coat, curved horns",
    "bug": "ladybug, red with black spots, on green leaf",
    "buggy": "baby stroller, four wheels, handle",
    "build": "7yo girl, curly red hair, freckles, stacking wooden blocks",
    "building": "simple house, red roof, door, two windows",
    "built": "finished house, complete with windows and door",
    "bulb": "light bulb, glowing yellow, screw base",
    "bull": "bull, muscular, hump, curved horns",
    "bullet": "bullet, copper casing, pointed tip",
    "bum": "human buttocks, clothed",
    "bumblebee": "bumblebee, black and yellow stripes, fuzzy body",
    "bump": "bump on head, red and swollen",
    "bun": "hamburger bun, round, sesame seeds on top",
    "bunch": "bunch of purple grapes, vine leaves",
    "bundle": "bundle of wheat stalks, tied with string",
    "bunny": "cute bunny rabbit, long ears, sitting",
    "burn": "candle flame, wax melting, bright orange fire",
    "burst": "balloon popping, rubber pieces flying, confetti",
    "bury": "person shoveling dirt over treasure chest, hole",
    "bus": "yellow school bus, windows, wheels, stop sign",
    "bush": "green bush, dense leaves, rounded shape",
    "bushel": "wooden bushel basket, filled with red apples",
    "business": "office building, glass windows, entrance doors",
    "busy": "15yo girl, curly red hair, freckles, juggling books, phone, backpack",
    "but": "happy face, but sad face, contrast",
    "butcher": "butcher in apron, holding meat cleaver, meat counter",
    "butter": "butter stick, yellow, wrapped in paper",
    "buttercup": "buttercup flower, yellow petals, green stem",
    "butterfly": "butterfly with colorful wings, black outline",
    "buttermilk": "glass of buttermilk, white liquid",
    "butterscotch": "butterscotch candy, golden brown, wrapped",
    "button": "round button, four holes, white",
    "buttonhole": "buttonhole on blue fabric, round opening",
    "buy": "7yo girl, curly red hair, freckles, holding shopping bag, smiling",
    "buzz": "bee flying with motion lines, wings blurred",
    "by": "7yo girl, curly red hair, freckles, standing next to small tree",
    "bye": "7yo girl, curly red hair, freckles, waving goodbye, smiling",
    "cab": "yellow taxi cab, checkered stripe, roof light",
    "cabbage": "whole green cabbage, round head, leaves",
    "cabin": "wooden cabin in forest, chimney, windows",
    "cabinet": "kitchen cabinet, wooden, two doors, handles",
    "cackle": "7yo girl, curly red hair, freckles, laughing loudly, head back",
    "cage": "metal bird cage with open door",
    "cake": "round birthday cake with candles",
    "calendar": "wall calendar showing December",
    "calf": "baby cow standing in grass",
    "call": "7yo girl, curly red hair, freckles, shouting with megaphone",
    "caller": "person holding phone to ear",
    "calling": "7yo girl, curly red hair, freckles, on phone",
    "came": "7yo girl, curly red hair, freckles, arriving at door",
    "camel": "camel with two humps",
    "camp": "tent in forest clearing",
    "campfire": "campfire with flames and logs",
    "can": "soda can with pull tab",
    "can't": "7yo girl, curly red hair, freckles, shaking head with crossed arms",
    "canal": "narrow canal with boats",
    "canary": "yellow canary on perch",
    "candle": "lit candle with flame, wax dripping",
    "candlestick": "metal candlestick with candle, decorative base",
    "candy": "colorful wrapped candy, shiny wrapper",
    "cane": "wooden cane with curved handle, rubber tip",
    "cannon": "old-fashioned cannon with wheels, barrel pointing up",
    "cannot": "7yo girl, curly red hair, freckles, shaking head no, hands up",
    "canoe": "wooden canoe on calm water, paddles inside",
    "canyon": "deep canyon with river at bottom, steep rock walls",
    "cap": "baseball cap with brim, adjustable strap",
    "cape": "superhero cape flowing in wind, red fabric",
    "capital": "city skyline with dome building, flag waving",
    "captain": "captain with hat and badge, standing tall",
    "car": "sedan car with four wheels, windows, headlights",
    "card": "playing card with heart symbol, number 7",
    "cardboard": "brown cardboard box, folded edges, texture",
    "care": "7yo girl, curly red hair, freckles, hugging teddy bear gently",
    "careful": "7yo girl, curly red hair, freckles, walking carefully on eggs",
    "careless": "7yo girl, curly red hair, freckles, dropping books carelessly",
    "carelessness": "7yo girl, curly red hair, freckles, spilling milk carelessly",
    "carload": "pile of toy cars",
    "carpenter": "15yo girl, curly red hair, freckles, wearing carpenter apron, holding hammer",
    "carpet": "patterned carpet with fringe",
    "carriage": "horse-drawn carriage with wheels",
    "carrot": "orange carrot with green leaves",
    "carry": "7yo girl, curly red hair, freckles, carrying stack of books",
    "cart": "wooden cart with two wheels",
    "carve": "15yo girl, curly red hair, freckles, carving pumpkin with knife",
    "case": "leather briefcase with handle",
    "cash": "stack of dollar bills",
    "cashier": "25yo woman, curly red hair, freckles, working at cash register",
    "castle": "medieval castle with tall towers and flags",
    "cat": "orange tabby cat sitting, tail curled",
    "catbird": "gray catbird with black cap and reddish undertail",
    "catch": "7yo girl, curly red hair, freckles, jumping to catch red ball",
    "catcher": "baseball catcher in full gear, squatting behind home plate",
    "caterpillar": "green caterpillar with yellow stripes crawling on leaf",
    "catfish": "catfish with long whiskers swimming underwater",
    "catsup": "red ketchup bottle with label, pouring onto plate",
    "cattle": "herd of black and white cows grazing in green field",
    "caught": "7yo girl, curly red hair, freckles, holding red ball with both hands",
    "cause": "7yo girl, curly red hair, freckles, pushing first domino in line",
    "cave": "dark cave entrance with stalactites and stalagmites",
    "ceiling": "white ceiling with ceiling fan and light fixture",
    "cell": "prison cell with metal bars and small window",
    "cellar": "stone cellar with wooden shelves and wine bottles",
    "cent": "penny coin, Lincoln side up",
    "center": "red bullseye target, arrow hitting center",
    "cereal": "bowl of cereal with milk, spoon",
    "certain": "7yo girl, curly red hair, freckles, nodding confidently, thumbs up",
    "certainly": "7yo girl, curly red hair, freckles, giving double thumbs up, big smile",
    "chain": "metal chain link, silver",
    "chair": "simple wooden chair, four legs",
    "chalk": "white chalk stick, broken tip",
    "champion": "7yo girl, curly red hair, freckles, holding trophy, medal around neck",
    "chance": "red dice showing six, lucky",
    "change": "caterpillar transforming into butterfly",
    "chap": "cracked lips, dry skin",
    "charge": "bull charging, horns down",
    "charm": "four-leaf clover, green",
    "chart": "bar chart, blue bars, title 'Sales'",
    "chase": "7yo girl, curly red hair, freckles, running fast, chasing a butterfly",
    "chatter": "7yo girl, curly red hair, freckles, mouth open, talking excitedly with friends",
    "cheap": "price tag showing $1, 7yo girl, curly red hair, freckles pointing at it",
    "cheat": "7yo girl, curly red hair, freckles, peeking at classmate's paper during test",
    "check": "7yo girl, curly red hair, freckles, checking items on a to-do list with pencil",
    "checkers": "checkerboard with red and black pieces, ready to play",
    "cheek": "7yo girl, curly red hair, freckles, profile view showing cheek",
    "cheer": "7yo girl, curly red hair, freckles, clapping hands, cheering with smile",
    "cheese": "slice of yellow cheese with holes",
    "cherry": "red cherry with green stem and leaf",
    "chest": "wooden treasure chest with metal bands and open lid",
    "chew": "7yo girl, curly red hair, freckles, chewing gum with mouth closed",
    "chick": "yellow baby chick with orange beak and feet",
    "chicken": "brown chicken with red comb and white feathers",
    "chief": "7yo girl, curly red hair, freckles, wearing chief's hat and badge",
    "child": "child, standing, smiling",
    "childhood": "7yo girl, curly red hair, freckles, playing with toys on floor",
    "children": "group of children, playing together",
    "chill": "15yo girl, curly red hair, freckles, teen style, lying on couch, relaxed",
    "chilly": "7yo girl, curly red hair, freckles, shivering, wearing scarf and mittens",
    "chimney": "brick chimney, smoke coming out top",
    "chin": "face, finger pointing to chin",
    "china": "fine china plate, floral pattern",
    "chip": "potato chip, crinkled",
    "chipmunk": "chipmunk, cheeks full of nuts",
    "chocolate": "chocolate bar, broken piece",
    "choice": "7yo girl, curly red hair, freckles, pointing at two different fruits",
    "choose": "7yo girl, curly red hair, freckles, picking apple from basket",
    "chop": "hand chopping carrot with knife on cutting board",
    "chorus": "group of people singing together, mouths open",
    "chose": "7yo girl, curly red hair, freckles, pointing at one apple from a pile",
    "chosen": "7yo girl, curly red hair, freckles, holding a golden star, others on table",
    "christen": "priest holding baby, water pouring from shell, church setting",
    "christmas": "Christmas tree with ornaments and presents underneath",
    "church": "white church with steeple and cross, simple design",
    "churn": "wooden butter churn with handle, milk inside",
    "circle": "perfect circle, no fill, thick black outline",
    "circus": "red and white striped circus tent with flags on top",
    "citizen": "15yo girl, curly red hair, freckles, teen style, holding small flag, smiling",
    "city": "city skyline with tall buildings, simple shapes",
    "clang": "hand striking large metal bell, vibration lines showing sound",
    "clap": "hands clapping together, motion lines showing action",
    "class": "classroom with desks and chalkboard, simple design",
    "classmate": "15yo girl, curly red hair, freckles, teen style, sitting with friend at desk",
    "classroom": "classroom with desks, chairs, blackboard, and globe",
    "claw": "cat's claw extended, sharp and curved",
    "clay": "clay on pottery wheel, wet and malleable",
    "clean": "7yo girl, curly red hair, freckles, wiping table with cloth, sparkling clean",
    "cleaner": "person in uniform holding spray bottle and cloth",
    "clear": "clear glass window, transparent with no distortion",
    "clerk": "clerk behind counter, wearing glasses, holding papers",
    "clever": "7yo girl, curly red hair, freckles, solving puzzle, lightbulb above head",
    "click": "computer mouse being clicked, button pressed down",
    "cliff": "tall cliff overlooking ocean, waves crashing below",
    "climb": "7yo girl, curly red hair, freckles, climbing ladder, reaching upward",
    "clip": "paper clip holding papers together, metal and bent",
    "cloak": "long cloak with hood, flowing fabric, dark color",
    "clock": "wall clock with round face, hour and minute hands",
    "close": "7yo girl, curly red hair, freckles, hugging teddy bear tightly",
    "closet": "wooden closet with closed doors",
    "cloth": "folded cloth on table",
    "clothes": "pile of folded clothes",
    "clothing": "hanging clothes on rack",
    "cloud": "fluffy white cloud in blue sky",
    "cloudy": "overcast sky with multiple white clouds",
    "clover": "green clover with four leaves",
    "clown": "clown with red nose, colorful wig, and polka dot costume",
    "club": "golf club with wooden handle",
    "cluck": "chicken clucking with open beak",
    "clump": "clump of grass and dirt",
    "coach": "sports coach with whistle and clipboard",
    "coal": "black coal piece with shiny surface",
    "coast": "beach coastline with waves and sand",
    "coat": "winter coat hanging on hook",
    "cob": "corn cob, yellow kernels, green husk",
    "cobbler": "peach cobbler, golden crust, bubbling fruit",
    "cocoa": "hot cocoa, marshmallows, steam rising",
    "coconut": "brown coconut, hairy husk, three holes",
    "cocoon": "silky cocoon, hanging from branch, leaves",
    "cod": "cod fish, white belly, brown spots, fins",
    "codfish": "cod fish, white belly, brown spots, fins",
    "coffee": "coffee beans, brown, aromatic, scoop",
    "coffeepot": "coffeepot, spout, handle, steam",
    "coin": "gold coin, embossed design, shiny",
    "cold": "7yo girl, curly red hair, freckles, shivering, arms crossed, breath visible",
    "collar": "dog collar, metal tag, buckle, leather",
    "college": "college building, columns, steps, academic",
    "color": "rainbow colors, red orange yellow green blue purple",
    "colored": "colored pencils, red blue green yellow, box",
    "colt": "young colt, long legs, standing in field",
    "column": "tall stone column, classical design, base and capital",
    "comb": "plastic comb with fine teeth, handle",
    "come": "7yo girl, curly red hair, freckles, walking toward viewer, arms open",
    "comfort": "7yo girl, curly red hair, freckles, wrapped in soft blanket, smiling",
    "comic": "colorful comic book, open pages showing cartoon characters",
    "coming": "7yo girl, curly red hair, freckles, running toward viewer, motion lines",
    "company": "group of children playing together, smiling",
    "compare": "7yo girl, curly red hair, freckles, holding apple in one hand, orange in other, looking between them",
    "conductor": "conductor with black suit and baton, leading orchestra",
    "cone": "waffle ice cream cone with scoops of ice cream",
    "connect": "hand plugging USB cable into laptop port",
    "coo": "pigeon with open beak, making soft cooing sound",
    "cook": "person stirring pot on stove, steam rising",
    "cooked": "plate of cooked spaghetti with tomato sauce and meatballs",
    "cookie": "chocolate chip cookie, round, with visible chips",
    "cookies": "stack of chocolate chip cookies, three cookies high",
    "cooking": "person stirring pot on stove, steam rising",
    "cool": "sunglasses, ice cube, blue background",
    "cooler": "red cooler with handle and wheels",
    "coop": "wooden chicken coop with chickens outside",
    "copper": "copper penny, brown metal coin",
    "copy": "person pressing button on copy machine",
    "cord": "power cord with three-prong plug",
    "cork": "wine bottle cork, cylindrical shape",
    "corn": "ear of corn with yellow kernels",
    "corner": "room corner where two walls meet",
    "correct": "person giving thumbs up, smiling",
    "cost": "price tag showing $5.99",
    "cot": "folding cot with thin mattress",
    "cottage": "cottage with chimney and flower garden",
    "cotton": "cotton plant with fluffy white bolls",
    "couch": "couch with cushions and throw pillows",
    "cough": "15yo girl, curly red hair, freckles, coughing into elbow",
    "could": "15yo girl, curly red hair, freckles, standing at fork in road, looking at two paths",
    "couldn't": "15yo girl, curly red hair, freckles, trying to lift heavy rock, straining",
    "count": "15yo girl, curly red hair, freckles, counting apples on table, finger pointing",
    "counter": "kitchen counter with cutting board and knife",
    "country": "map showing country borders, compass rose",
    "county": "map section showing county lines, small town icon",
    "course": "winding road through hills, sign showing direction",
    "court": "basketball court with hoop and lines",
    "cousin": "15yo girl, curly red hair, freckles, hugging younger girl, both smiling",
    "cover": "15yo girl, curly red hair, freckles, placing lid on pot",
    "cow": "cow with black and white spots, standing in field",
    "coward": "7yo girl, curly red hair, freckles, hiding behind hands, scared expression",
    "cowardly": "7yo girl, curly red hair, freckles, trembling, knees shaking, scared",
    "cowboy": "cowboy hat, boots, lasso, western style",
    "cozy": "7yo girl, curly red hair, freckles, wrapped in warm blanket, smiling",
    "crab": "red crab, claws spread, walking sideways",
    "crack": "crack in wall, jagged line, small",
    "cracker": "square cracker, holes, salt sprinkled",
    "cradle": "wooden cradle, baby sleeping inside, rocking",
    "cramps": "7yo girl, curly red hair, freckles, holding stomach, wincing in pain",
    "cranberry": "red cranberry berries, round, in cluster",
    "crank": "metal crank handle, turning, gears visible",
    "cranky": "7yo girl, curly red hair, freckles, frowning, arms crossed, annoyed",
    "crash": "car crash, metal twisted, smoke rising, emergency lights",
    "crawl": "7yo girl, curly red hair, freckles, crawling on hands and knees",
    "crazy": "7yo girl, curly red hair, freckles, wild eyes, tongue out, spinning",
    "cream": "bowl of whipped cream, dollop on top",
    "creamy": "7yo girl, curly red hair, freckles, licking spoon with creamy yogurt",
    "creek": "narrow creek flowing through forest",
    "creep": "7yo girl, curly red hair, freckles, creeping slowly on hands and knees",
    "crept": "7yo girl, curly red hair, freckles, having crept behind tree, peeking out",
    "cried": "7yo girl, curly red hair, freckles, crying, tears on cheeks",
    "cries": "7yo girl, curly red hair, freckles, crying loudly, tears streaming",
    "croak": "green frog, mouth open, croaking",
    "crook": "crooked wooden stick, bent shape",
    "crooked": "crooked tree, 7yo girl, curly red hair, freckles standing beside it",
    "crop": "wheat field, golden crops ready for harvest",
    "cross": "wooden cross, simple design",
    "cross-eyed": "7yo girl, curly red hair, freckles, cross-eyed, eyes pointing inward",
    "crossing": "zebra crossing, white stripes on road",
    "crow": "black crow, perched on tree branch",
    "crowd": "dense crowd of people, diverse ages, standing close together",
    "crowded": "packed subway car, people standing shoulder to shoulder",
    "crown": "golden crown with jewels, ornate design",
    "cruel": "15yo girl, curly red hair, freckles, smirking cruelly, arms crossed",
    "crumb": "small bread crumb, golden brown, on white table",
    "crumble": "cookie crumbling in hand, pieces falling",
    "crush": "aluminum can being crushed, metal bending",
    "crust": "pizza crust, golden brown, with cheese and pepperoni",
    "cry": "7yo girl, curly red hair, freckles, crying, tears on cheeks",
    "cub": "bear cub, fluffy, sitting on hind legs",
    "cuff": "shirt cuff, white fabric, with button",
    "cup": "coffee cup, white ceramic, with steam rising",
    "cupboard": "kitchen cupboard, wooden, with closed doors",
    "cupful": "measuring cup, filled to brim with flour",
    "cure": "medicine bottle, glass, with red cross label",
    "curl": "7yo girl, curly red hair, freckles, hair in tight curls",
    "curly": "7yo girl, curly red hair, freckles, hair in tight curls",
    "curtain": "fabric curtain with folds and tassels",
    "curve": "curved road with yellow line",
    "cushion": "decorative cushion with floral pattern",
    "custard": "bowl of yellow custard with spoon",
    "customer": "person holding shopping bag and wallet",
    "cut": "scissors cutting paper with zigzag line",
    "cute": "7yo girl, curly red hair, freckles, big sparkling eyes, smiling",
    "cutting": "scissors cutting paper with zigzag line",
    "dab": "7yo girl, curly red hair, freckles, doing dab pose, arm across face",
    "dad": "man with short hair, wearing glasses, smiling",
    "daddy": "man with short hair, wearing glasses, smiling",
    "daily": "calendar with daily checkmarks for 7 days",
    "dairy": "milk carton and cheese wheel",
    "daisy": "daisy flower, white petals, yellow center",
    "dam": "concrete dam holding back river water",
    "damage": "broken vase with cracks, pieces on floor",
    "dame": "elegant woman in formal dress, wearing hat",
    "damp": "slightly wet towel, water droplets visible",
    "dance": "15yo girl, curly red hair, freckles, dancing with arms raised",
    "dancer": "ballet dancer in tutu, standing on toes",
    "dancing": "15yo girl, curly red hair, freckles, spinning in dance pose",
    "dandy": "man in stylish suit, top hat, cane",
    "danger": "warning sign with exclamation mark, red background",
    "dangerous": "sharp broken glass, blood droplets on shards",
    "dare": "15yo girl, curly red hair, freckles, pointing finger, determined look",
    "dark": "dark room with single candle flame",
    "darkness": "pitch black space with glowing eyes",
    "darling": "25yo woman, curly red hair, freckles, hugging teddy bear, smiling",
    "darn": "7yo girl, curly red hair, freckles, stomping foot, arms crossed, frustrated",
    "dart": "dart with colorful fins, sharp tip",
    "dash": "7yo girl, curly red hair, freckles, running fast, arms pumping",
    "date": "bunch of dates, brown wrinkled fruit",
    "daughter": "7yo girl, curly red hair, freckles, hugging mother",
    "dawn": "sunrise over hills, orange sky, birds flying",
    "day": "bright sun in blue sky, white clouds",
    "daybreak": "early morning, sun peeking over horizon, soft light",
    "daytime": "bright sunny day, green grass, blue sky",
    "dead": "dead brown flower, wilted petals",
    "deaf": "7yo girl, curly red hair, freckles, covering ears, shaking head",
    "deal": "two hands shaking, business deal",
    "dear": "7yo girl, curly red hair, freckles, hugging teddy bear",
    "december": "snowy winter scene, pine trees, snowflakes",
    "decide": "7yo girl, curly red hair, freckles, pointing at two doors, one open, one closed",
    "deck": "wooden deck with railing, potted plants",
    "deed": "7yo girl, curly red hair, freckles, holding up certificate with gold seal",
    "deep": "DEEP stone well, tiny 7yo girl, curly red hair, freckles peering over edge",
    "deer": "male deer with large antlers, standing in forest",
    "defeat": "7yo girl, curly red hair, freckles, sitting on ground, chess pieces scattered around",
    "defend": "7yo girl, curly red hair, freckles, holding shield, protecting small bird",
    "defense": "wooden shield and helmet on stand",
    "delight": "7yo girl, curly red hair, freckles, jumping with arms up, confetti falling",
    "den": "bear standing at cave entrance, trees around",
    "dentist": "dentist in white coat, holding dental mirror and pick",
    "depend": "7yo girl, curly red hair, freckles, leaning on large tree, looking up",
    "deposit": "7yo girl, curly red hair, freckles, placing coin into piggy bank",
    "describe": "7yo girl, curly red hair, freckles, pointing at flower, talking to friend",
    "desert": "cactus in sand dunes, hot sun overhead",
    "deserve": "7yo girl, curly red hair, freckles, holding trophy, smiling proudly",
    "desire": "7yo girl, curly red hair, freckles, reaching for cookie jar on high shelf",
    "desk": "simple wooden desk with drawer",
    "destroy": "7yo girl, curly red hair, freckles, smashing wooden blocks with hammer",
    "devil": "cartoon devil with red skin, horns, and tail",
    "dew": "grass blade with morning dew drops",
    "diamond": "sparkling diamond with many facets",
    "did": "7yo girl, curly red hair, freckles, holding finished drawing, smiling",
    "didn't": "7yo girl, curly red hair, freckles, shaking head no, hands empty",
    "die": "7yo girl, curly red hair, freckles, lying down with eyes closed, peaceful",
    "died": "simple gravestone with flowers, peaceful scene",
    "dies": "7yo girl, curly red hair, freckles, lying down with eyes closed, peaceful",
    "difference": "apple and orange side by side, showing difference",
    "different": "red ball and blue ball, clearly different colors",
    "dig": "7yo girl, curly red hair, freckles, digging in sandbox with plastic shovel",
    "dim": "dimly lit room, single lamp casting soft glow",
    "dime": "US dime coin, silver, Roosevelt portrait",
    "dine": "person sitting at table, plate of food, fork in hand",
    "ding-dong": "doorbell button, sound waves radiating outward",
    "dinner": "plate with dinner, meat, vegetables, bread",
    "dip": "person dipping tortilla chip in salsa bowl",
    "direct": "person pointing forward, arm extended, finger indicating",
    "direction": "arrow pointing right, simple directional sign",
    "dirt": "pile of brown dirt, clumpy soil texture",
    "dirty": "hands covered in mud, dirty fingerprints visible",
    "discover": "person kneeling, uncovering buried treasure chest",
    "dish": "empty white plate, simple round dish",
    "dislike": "person making disgusted face, nose wrinkled, tongue out",
    "dismiss": "person waving hand, shooing motion, dismissing",
    "ditch": "roadside ditch, water flowing, grassy edges",
    "dive": "7yo girl, curly red hair, freckles, diving into pool, arms stretched forward",
    "diver": "scuba diver in full gear, oxygen tank, mask, fins",
    "divide": "pizza cut into 4 equal slices, 7yo girl, curly red hair, freckles pointing at slices",
    "do": "7yo girl, curly red hair, freckles, sitting at desk, writing in notebook",
    "dock": "wooden dock with boats tied to posts, calm water",
    "doctor": "doctor in white coat, stethoscope around neck, holding clipboard",
    "does": "15yo girl, curly red hair, freckles, teen style, washing dishes at sink",
    "doesn't": "15yo girl, curly red hair, freckles, teen style, shaking head no, arms crossed",
    "dog": "golden retriever dog, friendly expression, red collar",
    "doll": "rag doll with yarn hair, blue dress, button eyes",
    "dollar": "US one dollar bill, George Washington portrait",
    "dolly": "hand truck dolly with wheels, wooden platform",
    "don't": "25yo woman, curly red hair, freckles, adult style, waving finger no, stern expression",
    "done": "7yo girl, curly red hair, freckles, holding up completed worksheet, smiling",
    "donkey": "donkey with long ears, gray coat, standing in field",
    "door": "wooden door with handle",
    "doorbell": "doorbell button on wall",
    "doorknob": "round doorknob on wooden door",
    "doorstep": "stone doorstep with wooden door",
    "dot": "red dot on white background",
    "double": "two identical red apples side by side",
    "dough": "ball of bread dough on wooden table",
    "dove": "white dove flying with spread wings",
    "down": "7yo girl, curly red hair, freckles, pointing finger down",
    "downstairs": "wooden staircase with arrow pointing down",
    "downtown": "city skyline with tall buildings",
    "dozen": "carton of 12 eggs",
    "drag": "7yo girl, curly red hair, freckles, dragging heavy suitcase",
    "drain": "sink drain with water swirling down",
    "drank": "7yo girl, curly red hair, freckles, holding cup to mouth, drinking",
    "draw": "7yo girl, curly red hair, freckles, drawing with pencil on paper",
    "drawer": "open wooden drawer with folded clothes",
    "drawing": "colorful child's drawing of house and sun",
    "dream": "7yo girl, curly red hair, freckles, sleeping peacefully, thought bubble with stars",
    "dress": "simple summer dress on hanger",
    "dresser": "wooden dresser with mirror and drawers",
    "dressmaker": "15yo girl, curly red hair, freckles, teen style, sewing dress at machine",
    "drew": "7yo girl, curly red hair, freckles, holding up finished drawing proudly",
    "dried": "7yo girl, curly red hair, freckles, wrapped in towel after bath",
    "drift": "small boat drifting on calm water",
    "drill": "cordless power drill with drill bit",
    "drink": "glass of water with ice cubes",
    "drip": "water dripping from faucet into sink",
    "drive": "7yo girl, curly red hair, freckles, driving toy car",
    "driven": "7yo girl, curly red hair, freckles, pushing giant boulder uphill, determined expression",
    "driver": "7yo girl, curly red hair, freckles, sitting in car driver's seat, hands on steering wheel",
    "drop": "water droplet falling from leaf",
    "drove": "7yo girl, curly red hair, freckles, driving toy car down street",
    "drown": "7yo girl, curly red hair, freckles, struggling in water, arms waving",
    "drowsy": "7yo girl, curly red hair, freckles, yawning, holding pillow, eyes half-closed",
    "drub": "7yo girl, curly red hair, freckles, drumming on table with hands",
    "drum": "drum with drumsticks on top",
    "dry": "7yo girl, curly red hair, freckles, holding dry towel, desert background",
    "duck": "duck swimming in pond with lily pads",
    "due": "calendar showing circled date, 7yo girl, curly red hair, freckles, pointing at it",
    "dug": "7yo girl, curly red hair, freckles, holding shovel, dirt pile next to hole",
    "dull": "7yo girl, curly red hair, freckles, holding gray pencil, bored expression",
    "dumb": "7yo girl, curly red hair, freckles, scratching head, confused expression",
    "dump": "pile of trash bags and broken furniture",
    "during": "wall clock showing 3 o'clock, child playing nearby",
    "dust": "floating dust particles in sunbeam",
    "dusty": "old wooden shelf covered in dust, books and vase",
    "duty": "7yo girl, curly red hair, freckles, making bed, morning duty",
    "dwarf": "garden gnome with red hat and white beard",
    "dwell": "family house with smoke from chimney, garden",
    "dwelt": "old cottage with broken windows, abandoned",
    "dying": "wilting rose with drooping petals, brown edges",
    "each": "row of five red apples, each with green leaf",
    "eager": "7yo girl, curly red hair, freckles, jumping up and down, hands clapping",
    "eagle": "eagle soaring with spread wings, mountain background",
    "ear": "human ear with detailed inner structure visible",
    "early": "sunrise over hills, rooster crowing, morning mist",
    "earn": "15yo girl, curly red hair, freckles, holding trophy, smiling proudly",
    "earth": "Earth from space, blue marble with white clouds and green continents",
    "east": "Sun rising over horizon, rays spreading to the right",
    "eastern": "Japanese pagoda with curved roof, cherry blossoms",
    "easy": "7yo girl, curly red hair, freckles, smiling while stacking blocks",
    "eat": "7yo girl, curly red hair, freckles, eating ice cream cone",
    "eaten": "Half-eaten apple with bite marks, core visible",
    "edge": "Sharp cliff edge overlooking valley, rocks visible",
    "egg": "White chicken egg with brown speckles, whole",
    "eh": "7yo girl, curly red hair, freckles, shrugging shoulders, palms up",
    "eight": "Large numeral 8, bold and thick",
    "eighteen": "Large numeral 18, bold and thick",
    "eighth": "8th position in race, 7yo girl, curly red hair, freckles crossing finish line",
    "eighty": "Large numeral 80, bold and thick",
    "either": "Two identical ice cream cones, 7yo girl, curly red hair, freckles pointing at both",
    "elbow": "Human elbow joint, bent arm showing crease",
    "elder": "25yo woman, curly red hair, freckles, wearing glasses, holding cane, smiling",
    "eldest": "25yo woman, curly red hair, freckles, standing with two younger kids",
    "electric": "glowing light bulb, filament visible",
    "electricity": "lightning bolt striking ground",
    "elephant": "elephant with trunk raised high",
    "eleven": "eleven colorful balloons tied together",
    "elf": "elf with pointed ears, wearing green hat",
    "elm": "elm tree with serrated leaves",
    "else": "15yo girl, curly red hair, freckles, pointing to different path",
    "elsewhere": "15yo girl, curly red hair, freckles, looking at map with finger on different location",
    "empty": "empty glass on table",
    "end": "finish line with checkered flag",
    "ending": "open book showing last page with THE END text",
    "enemy": "15yo girl, curly red hair, freckles, facing away from another girl",
    "engine": "car engine with visible pistons and belts",
    "engineer": "engineer in hard hat holding blueprints",
    "english": "open book with English text, Union Jack flag",
    "enjoy": "7yo girl, curly red hair, freckles, laughing with hands clapping",
    "enough": "full plate of food, satisfied expression",
    "enter": "7yo girl, curly red hair, freckles, walking through open doorway",
    "envelope": "envelope with stamp and address",
    "equal": "balance scale perfectly balanced with two equal weights",
    "erase": "7yo girl, curly red hair, freckles, erasing pencil marks from paper",
    "eraser": "pink eraser with pencil shavings",
    "errand": "person carrying shopping bag and list",
    "escape": "7yo girl, curly red hair, freckles, climbing out of open window",
    "eve": "clock showing midnight, party hats and confetti",
    "even": "number line highlighting 2, 4, 6, 8, 10 as even numbers",
    "evening": "sunset with orange and purple sky, evening atmosphere",
    "ever": "clock showing past, present, and future times",
    "every": "group of different fruits, apple, banana, orange, grape",
    "everybody": "diverse group of people, different ages, genders, smiling",
    "everyday": "toothbrush, toothpaste, cup of coffee, morning routine items",
    "everyone": "diverse group of people, different ages, genders, smiling",
    "everything": "pile of different objects, toys, books, ball, blocks",
    "everywhere": "butterflies flying in sky, on flowers, in trees, everywhere",
    "evil": "dark shadowy figure with horns, menacing expression",
    "exact": "two identical puzzle pieces, perfect fit together",
    "except": "group of apples, one banana, except banana",
    "exchange": "two children trading toys, ball for doll",
    "excited": "7yo girl, curly red hair, freckles, jumping with arms up, big smile",
    "exciting": "roller coaster going down steep hill, people screaming with joy",
    "excuse": "7yo girl, curly red hair, freckles, hands up, shrugging, apologetic face",
    "exit": "green exit sign with arrow pointing right",
    "expect": "7yo girl, curly red hair, freckles, looking forward with hands clasped, hopeful",
    "explain": "15yo girl, curly red hair, freckles, pointing at chalkboard, explaining",
    "extra": "pizza with extra slice on side",
    "eye": "human eye, detailed iris and pupil",
    "eyebrow": "human eyebrow, thick and natural",
    "fable": "open book showing fox and grapes illustration",
    "face": "human face, front view, neutral expression",
    "facing": "7yo girl, curly red hair, freckles, facing forward, arms at sides",
    "fact": "open book with page showing true statement",
    "factory": "factory with smokestacks and conveyor belt",
    "fail": "7yo girl, curly red hair, freckles, sitting among fallen building blocks",
    "faint": "7yo girl, curly red hair, freckles, lying on floor, eyes closed, hand on forehead",
    "fair": "carnival with Ferris wheel and game booths",
    "fairy": "fairy with butterfly wings, holding magic wand",
    "faith": "7yo girl, curly red hair, freckles, hands clasped in prayer",
    "fake": "7yo girl, curly red hair, freckles, holding plastic flower, real flower beside it",
    "fall": "pile of colorful autumn leaves falling",
    "false": "broken light bulb, filament disconnected",
    "family": "parents and two children holding hands",
    "fan": "folding handheld fan, open",
    "fancy": "fancy hat with feathers and ribbon",
    "far": "distant mountain range on horizon",
    "far-off": "far-off island on distant horizon",
    "faraway": "faraway castle on distant hill",
    "fare": "bus ticket with price printed",
    "farm": "red barn with silo and fence",
    "farmer": "farmer in overalls holding pitchfork",
    "farming": "tractor plowing field with crops",
    "farther": "distant tree line, closer tree in foreground",
    "fashion": "fashion model walking runway in stylish outfit",
    "fast": "cheetah running at full speed",
    "fasten": "7yo girl, curly red hair, freckles, fastening seatbelt in car",
    "fat": "7yo girl, curly red hair, freckles, round belly, smiling",
    "father": "man holding child's hand, walking",
    "fault": "7yo girl, curly red hair, freckles, pointing at broken vase on floor",
    "favor": "7yo girl, curly red hair, freckles, helping carry heavy books",
    "favorite": "7yo girl, curly red hair, freckles, hugging teddy bear tightly",
    "fear": "7yo girl, curly red hair, freckles, hiding behind hands, large spider visible",
    "feast": "table covered with various foods, turkey, pies, fruits",
    "feather": "single feather, quill shape, soft texture",
    "february": "calendar page showing February, hearts and snowflakes",
    "fed": "7yo girl, curly red hair, freckles, feeding baby with bottle",
    "feed": "7yo girl, curly red hair, freckles, feeding ducks in pond",
    "feel": "7yo girl, curly red hair, freckles, feeling soft fabric with fingers",
    "feet": "pair of bare feet, toes visible",
    "fell": "7yo girl, curly red hair, freckles, lying on ground after fall",
    "fellow": "two men shaking hands, smiling",
    "felt": "7yo girl, curly red hair, freckles, looking sad, shoulders slumped",
    "fence": "wooden fence with posts and rails",
    "fever": "thermometer showing 102°F, red line high",
    "few": "three apples on table, spaced apart",
    "fib": "7yo girl, curly red hair, freckles, looking guilty, finger crossed behind back",
    "fiddle": "violin with bow, being played",
    "field": "grassy field with distant trees",
    "fife": "small wooden fife flute with finger holes",
    "fifteen": "number 15, with fifteen stars around it",
    "fifth": "five children in line, 5th child highlighted",
    "fifty": "number 50, with fifty dots arranged in rows",
    "fig": "purple fig with stem and leaf",
    "fight": "two boys in fighting stance, fists raised",
    "figure": "black silhouette of person standing",
    "file": "manila folder with papers inside",
    "fill": "7yo girl, curly red hair, freckles, pouring water into glass until full",
    "film": "movie camera with film strip coming out",
    "finally": "7yo girl, curly red hair, freckles, crossing finish line with ribbon breaking",
    "find": "7yo girl, curly red hair, freckles, holding magnifying glass over treasure chest",
    "fine": "7yo girl, curly red hair, freckles, giving thumbs up and smiling",
    "finger": "hand pointing with index finger",
    "finish": "7yo girl, curly red hair, freckles, crossing finish line with ribbon breaking",
    "fire": "campfire with orange flames and logs",
    "fireplace": "brick fireplace with fire burning inside",
    "first": "7yo girl, curly red hair, freckles, standing at starting line with number 1",
    "fish": "fish, simple cartoon style, fins and tail",
    "fisherman": "fisherman, hat, fishing rod, sitting on dock",
    "fist": "clenched fist, knuckles visible",
    "fit": "7yo girl, curly red hair, freckles, doing jumping jacks, happy",
    "fits": "round peg fitting perfectly into round hole",
    "five": "five fingers held up, palm facing forward",
    "fix": "7yo girl, curly red hair, freckles, using wrench to fix bicycle",
    "flag": "flag, waving in wind, simple design",
    "flake": "snowflake, six-pointed, detailed pattern",
    "flame": "flame, orange and yellow, flickering",
    "flap": "bird, wings flapping, in flight",
    "flash": "lightning bolt, zig-zag shape, bright yellow",
    "flashlight": "flashlight, beam of light shining forward",
    "flat": "flat pancake, perfectly round, no thickness",
    "flea": "flea, tiny, jumping, long legs",
    "flesh": "raw steak, red and marbled",
    "flew": "bird soaring through sky",
    "flies": "house flies buzzing around",
    "flight": "airplane with contrails in blue sky",
    "flip": "7yo girl, curly red hair, freckles, mid-air doing a front flip",
    "flip-flop": "pair of colorful flip-flops on sandy beach",
    "float": "7yo girl, curly red hair, freckles, floating on back in pool",
    "flock": "flock of birds flying in V-formation",
    "flood": "street flooded with water, cars partially submerged",
    "floor": "wooden floor with colorful rug",
}