name: Update Manifest

on:
  push:
    paths:
      - 'styles/**/*.png'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: python3 scripts/gen_manifest.py
      - run: python3 scripts/create_symlinks.py
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
